/**
 * @fileoverview gRPC-Web generated client stub for health
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: health.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as health_pb from './health_pb'; // proto import: "health.proto"


export class HealthClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCheck = new grpcWeb.MethodDescriptor(
    '/health.Health/Check',
    grpcWeb.MethodType.UNARY,
    health_pb.HealthCheckRequest,
    health_pb.HealthCheckResponse,
    (request: health_pb.HealthCheckRequest) => {
      return request.serializeBinary();
    },
    health_pb.HealthCheckResponse.deserializeBinary
  );

  check(
    request: health_pb.HealthCheckRequest,
    metadata?: grpcWeb.Metadata | null): Promise<health_pb.HealthCheckResponse>;

  check(
    request: health_pb.HealthCheckRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: health_pb.HealthCheckResponse) => void): grpcWeb.ClientReadableStream<health_pb.HealthCheckResponse>;

  check(
    request: health_pb.HealthCheckRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: health_pb.HealthCheckResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/health.Health/Check',
        request,
        metadata || {},
        this.methodDescriptorCheck,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/health.Health/Check',
    request,
    metadata || {},
    this.methodDescriptorCheck);
  }

}

