/**
 * @fileoverview gRPC-Web generated client stub for orchestrator
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: orchestrator.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as orchestrator_pb from './orchestrator_pb'; // proto import: "orchestrator.proto"


export class OrchestratorClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSend = new grpcWeb.MethodDescriptor(
    '/orchestrator.Orchestrator/Send',
    grpcWeb.MethodType.UNARY,
    orchestrator_pb.ORequest,
    orchestrator_pb.OResponse,
    (request: orchestrator_pb.ORequest) => {
      return request.serializeBinary();
    },
    orchestrator_pb.OResponse.deserializeBinary
  );

  send(
    request: orchestrator_pb.ORequest,
    metadata?: grpcWeb.Metadata | null): Promise<orchestrator_pb.OResponse>;

  send(
    request: orchestrator_pb.ORequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: orchestrator_pb.OResponse) => void): grpcWeb.ClientReadableStream<orchestrator_pb.OResponse>;

  send(
    request: orchestrator_pb.ORequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: orchestrator_pb.OResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/orchestrator.Orchestrator/Send',
        request,
        metadata || {},
        this.methodDescriptorSend,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/orchestrator.Orchestrator/Send',
    request,
    metadata || {},
    this.methodDescriptorSend);
  }

}

