// source: orchestrator.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.orchestrator.Action', null, global);
goog.exportSymbol('proto.orchestrator.ORequest', null, global);
goog.exportSymbol('proto.orchestrator.ORequest.PayloadCase', null, global);
goog.exportSymbol('proto.orchestrator.OResponse', null, global);
goog.exportSymbol('proto.orchestrator.OResponse.ResultCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.orchestrator.ORequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.orchestrator.ORequest.oneofGroups_);
};
goog.inherits(proto.orchestrator.ORequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.orchestrator.ORequest.displayName = 'proto.orchestrator.ORequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.orchestrator.OResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.orchestrator.OResponse.oneofGroups_);
};
goog.inherits(proto.orchestrator.OResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.orchestrator.OResponse.displayName = 'proto.orchestrator.OResponse';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.orchestrator.ORequest.oneofGroups_ = [[3,4,5,6]];

/**
 * @enum {number}
 */
proto.orchestrator.ORequest.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  STRING_PAYLOAD: 3,
  NUMBER_PAYLOAD: 4,
  BOOLEAN_PAYLOAD: 5,
  BYTES_PAYLOAD: 6
};

/**
 * @return {proto.orchestrator.ORequest.PayloadCase}
 */
proto.orchestrator.ORequest.prototype.getPayloadCase = function() {
  return /** @type {proto.orchestrator.ORequest.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.orchestrator.ORequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.orchestrator.ORequest.prototype.toObject = function(opt_includeInstance) {
  return proto.orchestrator.ORequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.orchestrator.ORequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.orchestrator.ORequest.toObject = function(includeInstance, msg) {
  var f, obj = {
action: jspb.Message.getFieldWithDefault(msg, 1, 0),
objectName: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
stringPayload: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
numberPayload: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
booleanPayload: (f = jspb.Message.getBooleanField(msg, 5)) == null ? undefined : f,
bytesPayload: msg.getBytesPayload_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.orchestrator.ORequest}
 */
proto.orchestrator.ORequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.orchestrator.ORequest;
  return proto.orchestrator.ORequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.orchestrator.ORequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.orchestrator.ORequest}
 */
proto.orchestrator.ORequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.orchestrator.Action} */ (reader.readEnum());
      msg.setAction(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setObjectName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setStringPayload(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNumberPayload(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBooleanPayload(value);
      break;
    case 6:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBytesPayload(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.orchestrator.ORequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.orchestrator.ORequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.orchestrator.ORequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.orchestrator.ORequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAction();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeBool(
      5,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeBytes(
      6,
      f
    );
  }
};


/**
 * optional Action action = 1;
 * @return {!proto.orchestrator.Action}
 */
proto.orchestrator.ORequest.prototype.getAction = function() {
  return /** @type {!proto.orchestrator.Action} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.orchestrator.Action} value
 * @return {!proto.orchestrator.ORequest} returns this
 */
proto.orchestrator.ORequest.prototype.setAction = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string object_name = 2;
 * @return {string}
 */
proto.orchestrator.ORequest.prototype.getObjectName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.orchestrator.ORequest} returns this
 */
proto.orchestrator.ORequest.prototype.setObjectName = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.orchestrator.ORequest} returns this
 */
proto.orchestrator.ORequest.prototype.clearObjectName = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.orchestrator.ORequest.prototype.hasObjectName = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string string_payload = 3;
 * @return {string}
 */
proto.orchestrator.ORequest.prototype.getStringPayload = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.orchestrator.ORequest} returns this
 */
proto.orchestrator.ORequest.prototype.setStringPayload = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.orchestrator.ORequest.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.orchestrator.ORequest} returns this
 */
proto.orchestrator.ORequest.prototype.clearStringPayload = function() {
  return jspb.Message.setOneofField(this, 3, proto.orchestrator.ORequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.orchestrator.ORequest.prototype.hasStringPayload = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int64 number_payload = 4;
 * @return {number}
 */
proto.orchestrator.ORequest.prototype.getNumberPayload = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.orchestrator.ORequest} returns this
 */
proto.orchestrator.ORequest.prototype.setNumberPayload = function(value) {
  return jspb.Message.setOneofField(this, 4, proto.orchestrator.ORequest.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.orchestrator.ORequest} returns this
 */
proto.orchestrator.ORequest.prototype.clearNumberPayload = function() {
  return jspb.Message.setOneofField(this, 4, proto.orchestrator.ORequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.orchestrator.ORequest.prototype.hasNumberPayload = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bool boolean_payload = 5;
 * @return {boolean}
 */
proto.orchestrator.ORequest.prototype.getBooleanPayload = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.orchestrator.ORequest} returns this
 */
proto.orchestrator.ORequest.prototype.setBooleanPayload = function(value) {
  return jspb.Message.setOneofField(this, 5, proto.orchestrator.ORequest.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.orchestrator.ORequest} returns this
 */
proto.orchestrator.ORequest.prototype.clearBooleanPayload = function() {
  return jspb.Message.setOneofField(this, 5, proto.orchestrator.ORequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.orchestrator.ORequest.prototype.hasBooleanPayload = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bytes bytes_payload = 6;
 * @return {!(string|Uint8Array)}
 */
proto.orchestrator.ORequest.prototype.getBytesPayload = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * optional bytes bytes_payload = 6;
 * This is a type-conversion wrapper around `getBytesPayload()`
 * @return {string}
 */
proto.orchestrator.ORequest.prototype.getBytesPayload_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBytesPayload()));
};


/**
 * optional bytes bytes_payload = 6;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBytesPayload()`
 * @return {!Uint8Array}
 */
proto.orchestrator.ORequest.prototype.getBytesPayload_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBytesPayload()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.orchestrator.ORequest} returns this
 */
proto.orchestrator.ORequest.prototype.setBytesPayload = function(value) {
  return jspb.Message.setOneofField(this, 6, proto.orchestrator.ORequest.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.orchestrator.ORequest} returns this
 */
proto.orchestrator.ORequest.prototype.clearBytesPayload = function() {
  return jspb.Message.setOneofField(this, 6, proto.orchestrator.ORequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.orchestrator.ORequest.prototype.hasBytesPayload = function() {
  return jspb.Message.getField(this, 6) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.orchestrator.OResponse.oneofGroups_ = [[3,4,5,6]];

/**
 * @enum {number}
 */
proto.orchestrator.OResponse.ResultCase = {
  RESULT_NOT_SET: 0,
  STRING_RESULT: 3,
  NUMBER_RESULT: 4,
  BOOLEAN_RESULT: 5,
  BYTES_RESULT: 6
};

/**
 * @return {proto.orchestrator.OResponse.ResultCase}
 */
proto.orchestrator.OResponse.prototype.getResultCase = function() {
  return /** @type {proto.orchestrator.OResponse.ResultCase} */(jspb.Message.computeOneofCase(this, proto.orchestrator.OResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.orchestrator.OResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.orchestrator.OResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.orchestrator.OResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.orchestrator.OResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
status: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
message: jspb.Message.getFieldWithDefault(msg, 2, ""),
stringResult: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
numberResult: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
booleanResult: (f = jspb.Message.getBooleanField(msg, 5)) == null ? undefined : f,
bytesResult: msg.getBytesResult_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.orchestrator.OResponse}
 */
proto.orchestrator.OResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.orchestrator.OResponse;
  return proto.orchestrator.OResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.orchestrator.OResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.orchestrator.OResponse}
 */
proto.orchestrator.OResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setStatus(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setStringResult(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNumberResult(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBooleanResult(value);
      break;
    case 6:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBytesResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.orchestrator.OResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.orchestrator.OResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.orchestrator.OResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.orchestrator.OResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeBool(
      5,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeBytes(
      6,
      f
    );
  }
};


/**
 * optional bool status = 1;
 * @return {boolean}
 */
proto.orchestrator.OResponse.prototype.getStatus = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.orchestrator.OResponse} returns this
 */
proto.orchestrator.OResponse.prototype.setStatus = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.orchestrator.OResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.orchestrator.OResponse} returns this
 */
proto.orchestrator.OResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string string_result = 3;
 * @return {string}
 */
proto.orchestrator.OResponse.prototype.getStringResult = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.orchestrator.OResponse} returns this
 */
proto.orchestrator.OResponse.prototype.setStringResult = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.orchestrator.OResponse.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.orchestrator.OResponse} returns this
 */
proto.orchestrator.OResponse.prototype.clearStringResult = function() {
  return jspb.Message.setOneofField(this, 3, proto.orchestrator.OResponse.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.orchestrator.OResponse.prototype.hasStringResult = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int64 number_result = 4;
 * @return {number}
 */
proto.orchestrator.OResponse.prototype.getNumberResult = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.orchestrator.OResponse} returns this
 */
proto.orchestrator.OResponse.prototype.setNumberResult = function(value) {
  return jspb.Message.setOneofField(this, 4, proto.orchestrator.OResponse.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.orchestrator.OResponse} returns this
 */
proto.orchestrator.OResponse.prototype.clearNumberResult = function() {
  return jspb.Message.setOneofField(this, 4, proto.orchestrator.OResponse.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.orchestrator.OResponse.prototype.hasNumberResult = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bool boolean_result = 5;
 * @return {boolean}
 */
proto.orchestrator.OResponse.prototype.getBooleanResult = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.orchestrator.OResponse} returns this
 */
proto.orchestrator.OResponse.prototype.setBooleanResult = function(value) {
  return jspb.Message.setOneofField(this, 5, proto.orchestrator.OResponse.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.orchestrator.OResponse} returns this
 */
proto.orchestrator.OResponse.prototype.clearBooleanResult = function() {
  return jspb.Message.setOneofField(this, 5, proto.orchestrator.OResponse.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.orchestrator.OResponse.prototype.hasBooleanResult = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bytes bytes_result = 6;
 * @return {!(string|Uint8Array)}
 */
proto.orchestrator.OResponse.prototype.getBytesResult = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * optional bytes bytes_result = 6;
 * This is a type-conversion wrapper around `getBytesResult()`
 * @return {string}
 */
proto.orchestrator.OResponse.prototype.getBytesResult_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBytesResult()));
};


/**
 * optional bytes bytes_result = 6;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBytesResult()`
 * @return {!Uint8Array}
 */
proto.orchestrator.OResponse.prototype.getBytesResult_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBytesResult()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.orchestrator.OResponse} returns this
 */
proto.orchestrator.OResponse.prototype.setBytesResult = function(value) {
  return jspb.Message.setOneofField(this, 6, proto.orchestrator.OResponse.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.orchestrator.OResponse} returns this
 */
proto.orchestrator.OResponse.prototype.clearBytesResult = function() {
  return jspb.Message.setOneofField(this, 6, proto.orchestrator.OResponse.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.orchestrator.OResponse.prototype.hasBytesResult = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * @enum {number}
 */
proto.orchestrator.Action = {
  CREATE: 0,
  READ: 1,
  UPDATE: 2,
  DELETE: 3
};

goog.object.extend(exports, proto.orchestrator);
