// source: shared/common.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.shared.v1.Error', null, global);
goog.exportSymbol('proto.shared.v1.ErrorCode', null, global);
goog.exportSymbol('proto.shared.v1.Property', null, global);
goog.exportSymbol('proto.shared.v1.Property.ValueCase', null, global);
goog.exportSymbol('proto.shared.v1.ResponseMeta', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.shared.v1.ResponseMeta = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.shared.v1.ResponseMeta, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.shared.v1.ResponseMeta.displayName = 'proto.shared.v1.ResponseMeta';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.shared.v1.Error = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.shared.v1.Error, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.shared.v1.Error.displayName = 'proto.shared.v1.Error';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.shared.v1.Property = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.shared.v1.Property.oneofGroups_);
};
goog.inherits(proto.shared.v1.Property, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.shared.v1.Property.displayName = 'proto.shared.v1.Property';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.shared.v1.ResponseMeta.prototype.toObject = function(opt_includeInstance) {
  return proto.shared.v1.ResponseMeta.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.shared.v1.ResponseMeta} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.ResponseMeta.toObject = function(includeInstance, msg) {
  var f, obj = {
requestUid: jspb.Message.getFieldWithDefault(msg, 1, ""),
timestampMs: jspb.Message.getFieldWithDefault(msg, 2, 0),
sessionId: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.shared.v1.ResponseMeta}
 */
proto.shared.v1.ResponseMeta.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.shared.v1.ResponseMeta;
  return proto.shared.v1.ResponseMeta.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.shared.v1.ResponseMeta} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.shared.v1.ResponseMeta}
 */
proto.shared.v1.ResponseMeta.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestUid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestampMs(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessionId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.shared.v1.ResponseMeta.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.shared.v1.ResponseMeta.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.shared.v1.ResponseMeta} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.ResponseMeta.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestUid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTimestampMs();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getSessionId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string request_uid = 1;
 * @return {string}
 */
proto.shared.v1.ResponseMeta.prototype.getRequestUid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.shared.v1.ResponseMeta} returns this
 */
proto.shared.v1.ResponseMeta.prototype.setRequestUid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 timestamp_ms = 2;
 * @return {number}
 */
proto.shared.v1.ResponseMeta.prototype.getTimestampMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.shared.v1.ResponseMeta} returns this
 */
proto.shared.v1.ResponseMeta.prototype.setTimestampMs = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string session_id = 3;
 * @return {string}
 */
proto.shared.v1.ResponseMeta.prototype.getSessionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.shared.v1.ResponseMeta} returns this
 */
proto.shared.v1.ResponseMeta.prototype.setSessionId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.shared.v1.Error.prototype.toObject = function(opt_includeInstance) {
  return proto.shared.v1.Error.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.shared.v1.Error} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.Error.toObject = function(includeInstance, msg) {
  var f, obj = {
code: jspb.Message.getFieldWithDefault(msg, 1, 0),
message: jspb.Message.getFieldWithDefault(msg, 2, ""),
detail: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.shared.v1.Error}
 */
proto.shared.v1.Error.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.shared.v1.Error;
  return proto.shared.v1.Error.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.shared.v1.Error} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.shared.v1.Error}
 */
proto.shared.v1.Error.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.shared.v1.ErrorCode} */ (reader.readEnum());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDetail(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.shared.v1.Error.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.shared.v1.Error.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.shared.v1.Error} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.Error.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCode();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDetail();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional ErrorCode code = 1;
 * @return {!proto.shared.v1.ErrorCode}
 */
proto.shared.v1.Error.prototype.getCode = function() {
  return /** @type {!proto.shared.v1.ErrorCode} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.shared.v1.ErrorCode} value
 * @return {!proto.shared.v1.Error} returns this
 */
proto.shared.v1.Error.prototype.setCode = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.shared.v1.Error.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.shared.v1.Error} returns this
 */
proto.shared.v1.Error.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string detail = 3;
 * @return {string}
 */
proto.shared.v1.Error.prototype.getDetail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.shared.v1.Error} returns this
 */
proto.shared.v1.Error.prototype.setDetail = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.shared.v1.Property.oneofGroups_ = [[2,3,4,5,6,7]];

/**
 * @enum {number}
 */
proto.shared.v1.Property.ValueCase = {
  VALUE_NOT_SET: 0,
  STRING_PAYLOAD: 2,
  INT_PAYLOAD: 3,
  FLOAT_PAYLOAD: 4,
  BOOLEAN_PAYLOAD: 5,
  BYTES_PAYLOAD: 6,
  JSON_PAYLOAD: 7
};

/**
 * @return {proto.shared.v1.Property.ValueCase}
 */
proto.shared.v1.Property.prototype.getValueCase = function() {
  return /** @type {proto.shared.v1.Property.ValueCase} */(jspb.Message.computeOneofCase(this, proto.shared.v1.Property.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.shared.v1.Property.prototype.toObject = function(opt_includeInstance) {
  return proto.shared.v1.Property.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.shared.v1.Property} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.Property.toObject = function(includeInstance, msg) {
  var f, obj = {
key: jspb.Message.getFieldWithDefault(msg, 1, ""),
stringPayload: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
intPayload: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
floatPayload: (f = jspb.Message.getOptionalFloatingPointField(msg, 4)) == null ? undefined : f,
booleanPayload: (f = jspb.Message.getBooleanField(msg, 5)) == null ? undefined : f,
bytesPayload: msg.getBytesPayload_asB64(),
jsonPayload: (f = jspb.Message.getField(msg, 7)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.shared.v1.Property}
 */
proto.shared.v1.Property.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.shared.v1.Property;
  return proto.shared.v1.Property.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.shared.v1.Property} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.shared.v1.Property}
 */
proto.shared.v1.Property.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStringPayload(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setIntPayload(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setFloatPayload(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBooleanPayload(value);
      break;
    case 6:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBytesPayload(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setJsonPayload(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.shared.v1.Property.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.shared.v1.Property.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.shared.v1.Property} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.Property.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeBool(
      5,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeBytes(
      6,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional string key = 1;
 * @return {string}
 */
proto.shared.v1.Property.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.shared.v1.Property} returns this
 */
proto.shared.v1.Property.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string string_payload = 2;
 * @return {string}
 */
proto.shared.v1.Property.prototype.getStringPayload = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.shared.v1.Property} returns this
 */
proto.shared.v1.Property.prototype.setStringPayload = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.shared.v1.Property.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.shared.v1.Property} returns this
 */
proto.shared.v1.Property.prototype.clearStringPayload = function() {
  return jspb.Message.setOneofField(this, 2, proto.shared.v1.Property.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.shared.v1.Property.prototype.hasStringPayload = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int64 int_payload = 3;
 * @return {number}
 */
proto.shared.v1.Property.prototype.getIntPayload = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.shared.v1.Property} returns this
 */
proto.shared.v1.Property.prototype.setIntPayload = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.shared.v1.Property.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.shared.v1.Property} returns this
 */
proto.shared.v1.Property.prototype.clearIntPayload = function() {
  return jspb.Message.setOneofField(this, 3, proto.shared.v1.Property.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.shared.v1.Property.prototype.hasIntPayload = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional double float_payload = 4;
 * @return {number}
 */
proto.shared.v1.Property.prototype.getFloatPayload = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.shared.v1.Property} returns this
 */
proto.shared.v1.Property.prototype.setFloatPayload = function(value) {
  return jspb.Message.setOneofField(this, 4, proto.shared.v1.Property.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.shared.v1.Property} returns this
 */
proto.shared.v1.Property.prototype.clearFloatPayload = function() {
  return jspb.Message.setOneofField(this, 4, proto.shared.v1.Property.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.shared.v1.Property.prototype.hasFloatPayload = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bool boolean_payload = 5;
 * @return {boolean}
 */
proto.shared.v1.Property.prototype.getBooleanPayload = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.shared.v1.Property} returns this
 */
proto.shared.v1.Property.prototype.setBooleanPayload = function(value) {
  return jspb.Message.setOneofField(this, 5, proto.shared.v1.Property.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.shared.v1.Property} returns this
 */
proto.shared.v1.Property.prototype.clearBooleanPayload = function() {
  return jspb.Message.setOneofField(this, 5, proto.shared.v1.Property.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.shared.v1.Property.prototype.hasBooleanPayload = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bytes bytes_payload = 6;
 * @return {!(string|Uint8Array)}
 */
proto.shared.v1.Property.prototype.getBytesPayload = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * optional bytes bytes_payload = 6;
 * This is a type-conversion wrapper around `getBytesPayload()`
 * @return {string}
 */
proto.shared.v1.Property.prototype.getBytesPayload_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBytesPayload()));
};


/**
 * optional bytes bytes_payload = 6;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBytesPayload()`
 * @return {!Uint8Array}
 */
proto.shared.v1.Property.prototype.getBytesPayload_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBytesPayload()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.shared.v1.Property} returns this
 */
proto.shared.v1.Property.prototype.setBytesPayload = function(value) {
  return jspb.Message.setOneofField(this, 6, proto.shared.v1.Property.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.shared.v1.Property} returns this
 */
proto.shared.v1.Property.prototype.clearBytesPayload = function() {
  return jspb.Message.setOneofField(this, 6, proto.shared.v1.Property.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.shared.v1.Property.prototype.hasBytesPayload = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string json_payload = 7;
 * @return {string}
 */
proto.shared.v1.Property.prototype.getJsonPayload = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.shared.v1.Property} returns this
 */
proto.shared.v1.Property.prototype.setJsonPayload = function(value) {
  return jspb.Message.setOneofField(this, 7, proto.shared.v1.Property.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.shared.v1.Property} returns this
 */
proto.shared.v1.Property.prototype.clearJsonPayload = function() {
  return jspb.Message.setOneofField(this, 7, proto.shared.v1.Property.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.shared.v1.Property.prototype.hasJsonPayload = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * @enum {number}
 */
proto.shared.v1.ErrorCode = {
  ERROR_CODE_UNSPECIFIED: 0,
  ERROR_CODE_INVALID_INPUT: 1,
  ERROR_CODE_LLM_FAILURE: 2,
  ERROR_CODE_COMPUTATION_FAILURE: 3,
  ERROR_CODE_NOT_FOUND: 4
};

goog.object.extend(exports, proto.shared.v1);
