// source: shared/graph.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var shared_common_pb = require('../shared/common_pb.js');
goog.object.extend(proto, shared_common_pb);
goog.exportSymbol('proto.shared.v1.EdgeKind', null, global);
goog.exportSymbol('proto.shared.v1.Graph', null, global);
goog.exportSymbol('proto.shared.v1.GraphEdge', null, global);
goog.exportSymbol('proto.shared.v1.GraphNode', null, global);
goog.exportSymbol('proto.shared.v1.NodeKind', null, global);
goog.exportSymbol('proto.shared.v1.NodePosition', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.shared.v1.GraphNode = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.shared.v1.GraphNode.repeatedFields_, null);
};
goog.inherits(proto.shared.v1.GraphNode, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.shared.v1.GraphNode.displayName = 'proto.shared.v1.GraphNode';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.shared.v1.GraphEdge = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.shared.v1.GraphEdge.repeatedFields_, null);
};
goog.inherits(proto.shared.v1.GraphEdge, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.shared.v1.GraphEdge.displayName = 'proto.shared.v1.GraphEdge';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.shared.v1.NodePosition = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.shared.v1.NodePosition, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.shared.v1.NodePosition.displayName = 'proto.shared.v1.NodePosition';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.shared.v1.Graph = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.shared.v1.Graph.repeatedFields_, null);
};
goog.inherits(proto.shared.v1.Graph, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.shared.v1.Graph.displayName = 'proto.shared.v1.Graph';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.shared.v1.GraphNode.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.shared.v1.GraphNode.prototype.toObject = function(opt_includeInstance) {
  return proto.shared.v1.GraphNode.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.shared.v1.GraphNode} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.GraphNode.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 1, ""),
label: jspb.Message.getFieldWithDefault(msg, 2, ""),
kind: jspb.Message.getFieldWithDefault(msg, 3, 0),
propertiesList: jspb.Message.toObjectList(msg.getPropertiesList(),
    shared_common_pb.Property.toObject, includeInstance),
position: (f = msg.getPosition()) && proto.shared.v1.NodePosition.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.shared.v1.GraphNode}
 */
proto.shared.v1.GraphNode.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.shared.v1.GraphNode;
  return proto.shared.v1.GraphNode.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.shared.v1.GraphNode} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.shared.v1.GraphNode}
 */
proto.shared.v1.GraphNode.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setLabel(value);
      break;
    case 3:
      var value = /** @type {!proto.shared.v1.NodeKind} */ (reader.readEnum());
      msg.setKind(value);
      break;
    case 4:
      var value = new shared_common_pb.Property;
      reader.readMessage(value,shared_common_pb.Property.deserializeBinaryFromReader);
      msg.addProperties(value);
      break;
    case 5:
      var value = new proto.shared.v1.NodePosition;
      reader.readMessage(value,proto.shared.v1.NodePosition.deserializeBinaryFromReader);
      msg.setPosition(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.shared.v1.GraphNode.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.shared.v1.GraphNode.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.shared.v1.GraphNode} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.GraphNode.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLabel();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getKind();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getPropertiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      shared_common_pb.Property.serializeBinaryToWriter
    );
  }
  f = message.getPosition();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.shared.v1.NodePosition.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.shared.v1.GraphNode.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.shared.v1.GraphNode} returns this
 */
proto.shared.v1.GraphNode.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string label = 2;
 * @return {string}
 */
proto.shared.v1.GraphNode.prototype.getLabel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.shared.v1.GraphNode} returns this
 */
proto.shared.v1.GraphNode.prototype.setLabel = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional NodeKind kind = 3;
 * @return {!proto.shared.v1.NodeKind}
 */
proto.shared.v1.GraphNode.prototype.getKind = function() {
  return /** @type {!proto.shared.v1.NodeKind} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.shared.v1.NodeKind} value
 * @return {!proto.shared.v1.GraphNode} returns this
 */
proto.shared.v1.GraphNode.prototype.setKind = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * repeated Property properties = 4;
 * @return {!Array<!proto.shared.v1.Property>}
 */
proto.shared.v1.GraphNode.prototype.getPropertiesList = function() {
  return /** @type{!Array<!proto.shared.v1.Property>} */ (
    jspb.Message.getRepeatedWrapperField(this, shared_common_pb.Property, 4));
};


/**
 * @param {!Array<!proto.shared.v1.Property>} value
 * @return {!proto.shared.v1.GraphNode} returns this
*/
proto.shared.v1.GraphNode.prototype.setPropertiesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.shared.v1.Property=} opt_value
 * @param {number=} opt_index
 * @return {!proto.shared.v1.Property}
 */
proto.shared.v1.GraphNode.prototype.addProperties = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.shared.v1.Property, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.shared.v1.GraphNode} returns this
 */
proto.shared.v1.GraphNode.prototype.clearPropertiesList = function() {
  return this.setPropertiesList([]);
};


/**
 * optional NodePosition position = 5;
 * @return {?proto.shared.v1.NodePosition}
 */
proto.shared.v1.GraphNode.prototype.getPosition = function() {
  return /** @type{?proto.shared.v1.NodePosition} */ (
    jspb.Message.getWrapperField(this, proto.shared.v1.NodePosition, 5));
};


/**
 * @param {?proto.shared.v1.NodePosition|undefined} value
 * @return {!proto.shared.v1.GraphNode} returns this
*/
proto.shared.v1.GraphNode.prototype.setPosition = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.shared.v1.GraphNode} returns this
 */
proto.shared.v1.GraphNode.prototype.clearPosition = function() {
  return this.setPosition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.shared.v1.GraphNode.prototype.hasPosition = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.shared.v1.GraphEdge.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.shared.v1.GraphEdge.prototype.toObject = function(opt_includeInstance) {
  return proto.shared.v1.GraphEdge.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.shared.v1.GraphEdge} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.GraphEdge.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 1, ""),
sourceId: jspb.Message.getFieldWithDefault(msg, 2, ""),
targetId: jspb.Message.getFieldWithDefault(msg, 3, ""),
kind: jspb.Message.getFieldWithDefault(msg, 4, 0),
weight: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
propertiesList: jspb.Message.toObjectList(msg.getPropertiesList(),
    shared_common_pb.Property.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.shared.v1.GraphEdge}
 */
proto.shared.v1.GraphEdge.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.shared.v1.GraphEdge;
  return proto.shared.v1.GraphEdge.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.shared.v1.GraphEdge} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.shared.v1.GraphEdge}
 */
proto.shared.v1.GraphEdge.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSourceId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTargetId(value);
      break;
    case 4:
      var value = /** @type {!proto.shared.v1.EdgeKind} */ (reader.readEnum());
      msg.setKind(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setWeight(value);
      break;
    case 6:
      var value = new shared_common_pb.Property;
      reader.readMessage(value,shared_common_pb.Property.deserializeBinaryFromReader);
      msg.addProperties(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.shared.v1.GraphEdge.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.shared.v1.GraphEdge.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.shared.v1.GraphEdge} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.GraphEdge.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSourceId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTargetId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getKind();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getWeight();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getPropertiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      shared_common_pb.Property.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.shared.v1.GraphEdge.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.shared.v1.GraphEdge} returns this
 */
proto.shared.v1.GraphEdge.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string source_id = 2;
 * @return {string}
 */
proto.shared.v1.GraphEdge.prototype.getSourceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.shared.v1.GraphEdge} returns this
 */
proto.shared.v1.GraphEdge.prototype.setSourceId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string target_id = 3;
 * @return {string}
 */
proto.shared.v1.GraphEdge.prototype.getTargetId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.shared.v1.GraphEdge} returns this
 */
proto.shared.v1.GraphEdge.prototype.setTargetId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional EdgeKind kind = 4;
 * @return {!proto.shared.v1.EdgeKind}
 */
proto.shared.v1.GraphEdge.prototype.getKind = function() {
  return /** @type {!proto.shared.v1.EdgeKind} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.shared.v1.EdgeKind} value
 * @return {!proto.shared.v1.GraphEdge} returns this
 */
proto.shared.v1.GraphEdge.prototype.setKind = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional double weight = 5;
 * @return {number}
 */
proto.shared.v1.GraphEdge.prototype.getWeight = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.shared.v1.GraphEdge} returns this
 */
proto.shared.v1.GraphEdge.prototype.setWeight = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * repeated Property properties = 6;
 * @return {!Array<!proto.shared.v1.Property>}
 */
proto.shared.v1.GraphEdge.prototype.getPropertiesList = function() {
  return /** @type{!Array<!proto.shared.v1.Property>} */ (
    jspb.Message.getRepeatedWrapperField(this, shared_common_pb.Property, 6));
};


/**
 * @param {!Array<!proto.shared.v1.Property>} value
 * @return {!proto.shared.v1.GraphEdge} returns this
*/
proto.shared.v1.GraphEdge.prototype.setPropertiesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.shared.v1.Property=} opt_value
 * @param {number=} opt_index
 * @return {!proto.shared.v1.Property}
 */
proto.shared.v1.GraphEdge.prototype.addProperties = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.shared.v1.Property, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.shared.v1.GraphEdge} returns this
 */
proto.shared.v1.GraphEdge.prototype.clearPropertiesList = function() {
  return this.setPropertiesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.shared.v1.NodePosition.prototype.toObject = function(opt_includeInstance) {
  return proto.shared.v1.NodePosition.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.shared.v1.NodePosition} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.NodePosition.toObject = function(includeInstance, msg) {
  var f, obj = {
x: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
y: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
z: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.shared.v1.NodePosition}
 */
proto.shared.v1.NodePosition.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.shared.v1.NodePosition;
  return proto.shared.v1.NodePosition.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.shared.v1.NodePosition} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.shared.v1.NodePosition}
 */
proto.shared.v1.NodePosition.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setX(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setY(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setZ(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.shared.v1.NodePosition.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.shared.v1.NodePosition.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.shared.v1.NodePosition} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.NodePosition.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getX();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getY();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getZ();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
};


/**
 * optional double x = 1;
 * @return {number}
 */
proto.shared.v1.NodePosition.prototype.getX = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.shared.v1.NodePosition} returns this
 */
proto.shared.v1.NodePosition.prototype.setX = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double y = 2;
 * @return {number}
 */
proto.shared.v1.NodePosition.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.shared.v1.NodePosition} returns this
 */
proto.shared.v1.NodePosition.prototype.setY = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double z = 3;
 * @return {number}
 */
proto.shared.v1.NodePosition.prototype.getZ = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.shared.v1.NodePosition} returns this
 */
proto.shared.v1.NodePosition.prototype.setZ = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.shared.v1.Graph.repeatedFields_ = [2,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.shared.v1.Graph.prototype.toObject = function(opt_includeInstance) {
  return proto.shared.v1.Graph.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.shared.v1.Graph} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.Graph.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 1, ""),
nodesList: jspb.Message.toObjectList(msg.getNodesList(),
    proto.shared.v1.GraphNode.toObject, includeInstance),
edgesList: jspb.Message.toObjectList(msg.getEdgesList(),
    proto.shared.v1.GraphEdge.toObject, includeInstance),
metaList: jspb.Message.toObjectList(msg.getMetaList(),
    shared_common_pb.Property.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.shared.v1.Graph}
 */
proto.shared.v1.Graph.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.shared.v1.Graph;
  return proto.shared.v1.Graph.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.shared.v1.Graph} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.shared.v1.Graph}
 */
proto.shared.v1.Graph.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.shared.v1.GraphNode;
      reader.readMessage(value,proto.shared.v1.GraphNode.deserializeBinaryFromReader);
      msg.addNodes(value);
      break;
    case 3:
      var value = new proto.shared.v1.GraphEdge;
      reader.readMessage(value,proto.shared.v1.GraphEdge.deserializeBinaryFromReader);
      msg.addEdges(value);
      break;
    case 4:
      var value = new shared_common_pb.Property;
      reader.readMessage(value,shared_common_pb.Property.deserializeBinaryFromReader);
      msg.addMeta(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.shared.v1.Graph.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.shared.v1.Graph.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.shared.v1.Graph} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.Graph.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNodesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.shared.v1.GraphNode.serializeBinaryToWriter
    );
  }
  f = message.getEdgesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.shared.v1.GraphEdge.serializeBinaryToWriter
    );
  }
  f = message.getMetaList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      shared_common_pb.Property.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.shared.v1.Graph.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.shared.v1.Graph} returns this
 */
proto.shared.v1.Graph.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated GraphNode nodes = 2;
 * @return {!Array<!proto.shared.v1.GraphNode>}
 */
proto.shared.v1.Graph.prototype.getNodesList = function() {
  return /** @type{!Array<!proto.shared.v1.GraphNode>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.shared.v1.GraphNode, 2));
};


/**
 * @param {!Array<!proto.shared.v1.GraphNode>} value
 * @return {!proto.shared.v1.Graph} returns this
*/
proto.shared.v1.Graph.prototype.setNodesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.shared.v1.GraphNode=} opt_value
 * @param {number=} opt_index
 * @return {!proto.shared.v1.GraphNode}
 */
proto.shared.v1.Graph.prototype.addNodes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.shared.v1.GraphNode, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.shared.v1.Graph} returns this
 */
proto.shared.v1.Graph.prototype.clearNodesList = function() {
  return this.setNodesList([]);
};


/**
 * repeated GraphEdge edges = 3;
 * @return {!Array<!proto.shared.v1.GraphEdge>}
 */
proto.shared.v1.Graph.prototype.getEdgesList = function() {
  return /** @type{!Array<!proto.shared.v1.GraphEdge>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.shared.v1.GraphEdge, 3));
};


/**
 * @param {!Array<!proto.shared.v1.GraphEdge>} value
 * @return {!proto.shared.v1.Graph} returns this
*/
proto.shared.v1.Graph.prototype.setEdgesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.shared.v1.GraphEdge=} opt_value
 * @param {number=} opt_index
 * @return {!proto.shared.v1.GraphEdge}
 */
proto.shared.v1.Graph.prototype.addEdges = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.shared.v1.GraphEdge, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.shared.v1.Graph} returns this
 */
proto.shared.v1.Graph.prototype.clearEdgesList = function() {
  return this.setEdgesList([]);
};


/**
 * repeated Property meta = 4;
 * @return {!Array<!proto.shared.v1.Property>}
 */
proto.shared.v1.Graph.prototype.getMetaList = function() {
  return /** @type{!Array<!proto.shared.v1.Property>} */ (
    jspb.Message.getRepeatedWrapperField(this, shared_common_pb.Property, 4));
};


/**
 * @param {!Array<!proto.shared.v1.Property>} value
 * @return {!proto.shared.v1.Graph} returns this
*/
proto.shared.v1.Graph.prototype.setMetaList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.shared.v1.Property=} opt_value
 * @param {number=} opt_index
 * @return {!proto.shared.v1.Property}
 */
proto.shared.v1.Graph.prototype.addMeta = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.shared.v1.Property, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.shared.v1.Graph} returns this
 */
proto.shared.v1.Graph.prototype.clearMetaList = function() {
  return this.setMetaList([]);
};


/**
 * @enum {number}
 */
proto.shared.v1.NodeKind = {
  NODE_KIND_UNSPECIFIED: 0,
  NODE_KIND_CONCEPT: 1,
  NODE_KIND_ENTITY: 2,
  NODE_KIND_SCENARIO: 3,
  NODE_KIND_ALGORITHM: 4
};

/**
 * @enum {number}
 */
proto.shared.v1.EdgeKind = {
  EDGE_KIND_UNSPECIFIED: 0,
  EDGE_KIND_INFLUENCES: 1,
  EDGE_KIND_DEPENDS_ON: 2,
  EDGE_KIND_ADJACENT: 3,
  EDGE_KIND_CONTAINS: 4,
  EDGE_KIND_CONFLICTS: 5,
  EDGE_KIND_SUPPORTS: 6
};

goog.object.extend(exports, proto.shared.v1);
