// source: shared/llm.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var shared_common_pb = require('../shared/common_pb.js');
goog.object.extend(proto, shared_common_pb);
var shared_graph_pb = require('../shared/graph_pb.js');
goog.object.extend(proto, shared_graph_pb);
goog.exportSymbol('proto.shared.v1.AlgorithmSuggestion', null, global);
goog.exportSymbol('proto.shared.v1.AlgorithmSuggestionRequest', null, global);
goog.exportSymbol('proto.shared.v1.AlgorithmSuggestionResponse', null, global);
goog.exportSymbol('proto.shared.v1.ModuleKind', null, global);
goog.exportSymbol('proto.shared.v1.StructureChunk', null, global);
goog.exportSymbol('proto.shared.v1.StructureChunk.PayloadCase', null, global);
goog.exportSymbol('proto.shared.v1.StructureRequest', null, global);
goog.exportSymbol('proto.shared.v1.StructureResponse', null, global);
goog.exportSymbol('proto.shared.v1.StructureTarget', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.shared.v1.StructureRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.shared.v1.StructureRequest.repeatedFields_, null);
};
goog.inherits(proto.shared.v1.StructureRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.shared.v1.StructureRequest.displayName = 'proto.shared.v1.StructureRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.shared.v1.StructureResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.shared.v1.StructureResponse.repeatedFields_, null);
};
goog.inherits(proto.shared.v1.StructureResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.shared.v1.StructureResponse.displayName = 'proto.shared.v1.StructureResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.shared.v1.StructureChunk = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.shared.v1.StructureChunk.oneofGroups_);
};
goog.inherits(proto.shared.v1.StructureChunk, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.shared.v1.StructureChunk.displayName = 'proto.shared.v1.StructureChunk';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.shared.v1.AlgorithmSuggestionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.shared.v1.AlgorithmSuggestionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.shared.v1.AlgorithmSuggestionRequest.displayName = 'proto.shared.v1.AlgorithmSuggestionRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.shared.v1.AlgorithmSuggestionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.shared.v1.AlgorithmSuggestionResponse.repeatedFields_, null);
};
goog.inherits(proto.shared.v1.AlgorithmSuggestionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.shared.v1.AlgorithmSuggestionResponse.displayName = 'proto.shared.v1.AlgorithmSuggestionResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.shared.v1.AlgorithmSuggestion = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.shared.v1.AlgorithmSuggestion.repeatedFields_, null);
};
goog.inherits(proto.shared.v1.AlgorithmSuggestion, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.shared.v1.AlgorithmSuggestion.displayName = 'proto.shared.v1.AlgorithmSuggestion';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.shared.v1.StructureRequest.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.shared.v1.StructureRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.shared.v1.StructureRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.shared.v1.StructureRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.StructureRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
rawInput: jspb.Message.getFieldWithDefault(msg, 1, ""),
target: jspb.Message.getFieldWithDefault(msg, 2, 0),
sessionId: jspb.Message.getFieldWithDefault(msg, 3, ""),
hintsList: jspb.Message.toObjectList(msg.getHintsList(),
    shared_common_pb.Property.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.shared.v1.StructureRequest}
 */
proto.shared.v1.StructureRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.shared.v1.StructureRequest;
  return proto.shared.v1.StructureRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.shared.v1.StructureRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.shared.v1.StructureRequest}
 */
proto.shared.v1.StructureRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRawInput(value);
      break;
    case 2:
      var value = /** @type {!proto.shared.v1.StructureTarget} */ (reader.readEnum());
      msg.setTarget(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessionId(value);
      break;
    case 4:
      var value = new shared_common_pb.Property;
      reader.readMessage(value,shared_common_pb.Property.deserializeBinaryFromReader);
      msg.addHints(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.shared.v1.StructureRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.shared.v1.StructureRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.shared.v1.StructureRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.StructureRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRawInput();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTarget();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getSessionId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getHintsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      shared_common_pb.Property.serializeBinaryToWriter
    );
  }
};


/**
 * optional string raw_input = 1;
 * @return {string}
 */
proto.shared.v1.StructureRequest.prototype.getRawInput = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.shared.v1.StructureRequest} returns this
 */
proto.shared.v1.StructureRequest.prototype.setRawInput = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional StructureTarget target = 2;
 * @return {!proto.shared.v1.StructureTarget}
 */
proto.shared.v1.StructureRequest.prototype.getTarget = function() {
  return /** @type {!proto.shared.v1.StructureTarget} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.shared.v1.StructureTarget} value
 * @return {!proto.shared.v1.StructureRequest} returns this
 */
proto.shared.v1.StructureRequest.prototype.setTarget = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string session_id = 3;
 * @return {string}
 */
proto.shared.v1.StructureRequest.prototype.getSessionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.shared.v1.StructureRequest} returns this
 */
proto.shared.v1.StructureRequest.prototype.setSessionId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated Property hints = 4;
 * @return {!Array<!proto.shared.v1.Property>}
 */
proto.shared.v1.StructureRequest.prototype.getHintsList = function() {
  return /** @type{!Array<!proto.shared.v1.Property>} */ (
    jspb.Message.getRepeatedWrapperField(this, shared_common_pb.Property, 4));
};


/**
 * @param {!Array<!proto.shared.v1.Property>} value
 * @return {!proto.shared.v1.StructureRequest} returns this
*/
proto.shared.v1.StructureRequest.prototype.setHintsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.shared.v1.Property=} opt_value
 * @param {number=} opt_index
 * @return {!proto.shared.v1.Property}
 */
proto.shared.v1.StructureRequest.prototype.addHints = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.shared.v1.Property, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.shared.v1.StructureRequest} returns this
 */
proto.shared.v1.StructureRequest.prototype.clearHintsList = function() {
  return this.setHintsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.shared.v1.StructureResponse.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.shared.v1.StructureResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.shared.v1.StructureResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.shared.v1.StructureResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.StructureResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
graph: (f = msg.getGraph()) && shared_graph_pb.Graph.toObject(includeInstance, f),
confidence: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
warningsList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
meta: (f = msg.getMeta()) && shared_common_pb.ResponseMeta.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.shared.v1.StructureResponse}
 */
proto.shared.v1.StructureResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.shared.v1.StructureResponse;
  return proto.shared.v1.StructureResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.shared.v1.StructureResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.shared.v1.StructureResponse}
 */
proto.shared.v1.StructureResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new shared_graph_pb.Graph;
      reader.readMessage(value,shared_graph_pb.Graph.deserializeBinaryFromReader);
      msg.setGraph(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setConfidence(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addWarnings(value);
      break;
    case 4:
      var value = new shared_common_pb.ResponseMeta;
      reader.readMessage(value,shared_common_pb.ResponseMeta.deserializeBinaryFromReader);
      msg.setMeta(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.shared.v1.StructureResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.shared.v1.StructureResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.shared.v1.StructureResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.StructureResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGraph();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      shared_graph_pb.Graph.serializeBinaryToWriter
    );
  }
  f = message.getConfidence();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getWarningsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getMeta();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      shared_common_pb.ResponseMeta.serializeBinaryToWriter
    );
  }
};


/**
 * optional Graph graph = 1;
 * @return {?proto.shared.v1.Graph}
 */
proto.shared.v1.StructureResponse.prototype.getGraph = function() {
  return /** @type{?proto.shared.v1.Graph} */ (
    jspb.Message.getWrapperField(this, shared_graph_pb.Graph, 1));
};


/**
 * @param {?proto.shared.v1.Graph|undefined} value
 * @return {!proto.shared.v1.StructureResponse} returns this
*/
proto.shared.v1.StructureResponse.prototype.setGraph = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.shared.v1.StructureResponse} returns this
 */
proto.shared.v1.StructureResponse.prototype.clearGraph = function() {
  return this.setGraph(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.shared.v1.StructureResponse.prototype.hasGraph = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional double confidence = 2;
 * @return {number}
 */
proto.shared.v1.StructureResponse.prototype.getConfidence = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.shared.v1.StructureResponse} returns this
 */
proto.shared.v1.StructureResponse.prototype.setConfidence = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * repeated string warnings = 3;
 * @return {!Array<string>}
 */
proto.shared.v1.StructureResponse.prototype.getWarningsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.shared.v1.StructureResponse} returns this
 */
proto.shared.v1.StructureResponse.prototype.setWarningsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.shared.v1.StructureResponse} returns this
 */
proto.shared.v1.StructureResponse.prototype.addWarnings = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.shared.v1.StructureResponse} returns this
 */
proto.shared.v1.StructureResponse.prototype.clearWarningsList = function() {
  return this.setWarningsList([]);
};


/**
 * optional ResponseMeta meta = 4;
 * @return {?proto.shared.v1.ResponseMeta}
 */
proto.shared.v1.StructureResponse.prototype.getMeta = function() {
  return /** @type{?proto.shared.v1.ResponseMeta} */ (
    jspb.Message.getWrapperField(this, shared_common_pb.ResponseMeta, 4));
};


/**
 * @param {?proto.shared.v1.ResponseMeta|undefined} value
 * @return {!proto.shared.v1.StructureResponse} returns this
*/
proto.shared.v1.StructureResponse.prototype.setMeta = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.shared.v1.StructureResponse} returns this
 */
proto.shared.v1.StructureResponse.prototype.clearMeta = function() {
  return this.setMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.shared.v1.StructureResponse.prototype.hasMeta = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.shared.v1.StructureChunk.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.shared.v1.StructureChunk.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  NODE: 1,
  EDGE: 2,
  WARNING: 3
};

/**
 * @return {proto.shared.v1.StructureChunk.PayloadCase}
 */
proto.shared.v1.StructureChunk.prototype.getPayloadCase = function() {
  return /** @type {proto.shared.v1.StructureChunk.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.shared.v1.StructureChunk.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.shared.v1.StructureChunk.prototype.toObject = function(opt_includeInstance) {
  return proto.shared.v1.StructureChunk.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.shared.v1.StructureChunk} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.StructureChunk.toObject = function(includeInstance, msg) {
  var f, obj = {
node: (f = msg.getNode()) && shared_graph_pb.GraphNode.toObject(includeInstance, f),
edge: (f = msg.getEdge()) && shared_graph_pb.GraphEdge.toObject(includeInstance, f),
warning: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
isFinal: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
confidence: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
meta: (f = msg.getMeta()) && shared_common_pb.ResponseMeta.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.shared.v1.StructureChunk}
 */
proto.shared.v1.StructureChunk.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.shared.v1.StructureChunk;
  return proto.shared.v1.StructureChunk.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.shared.v1.StructureChunk} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.shared.v1.StructureChunk}
 */
proto.shared.v1.StructureChunk.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new shared_graph_pb.GraphNode;
      reader.readMessage(value,shared_graph_pb.GraphNode.deserializeBinaryFromReader);
      msg.setNode(value);
      break;
    case 2:
      var value = new shared_graph_pb.GraphEdge;
      reader.readMessage(value,shared_graph_pb.GraphEdge.deserializeBinaryFromReader);
      msg.setEdge(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setWarning(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsFinal(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setConfidence(value);
      break;
    case 6:
      var value = new shared_common_pb.ResponseMeta;
      reader.readMessage(value,shared_common_pb.ResponseMeta.deserializeBinaryFromReader);
      msg.setMeta(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.shared.v1.StructureChunk.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.shared.v1.StructureChunk.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.shared.v1.StructureChunk} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.StructureChunk.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNode();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      shared_graph_pb.GraphNode.serializeBinaryToWriter
    );
  }
  f = message.getEdge();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      shared_graph_pb.GraphEdge.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getIsFinal();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getConfidence();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getMeta();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      shared_common_pb.ResponseMeta.serializeBinaryToWriter
    );
  }
};


/**
 * optional GraphNode node = 1;
 * @return {?proto.shared.v1.GraphNode}
 */
proto.shared.v1.StructureChunk.prototype.getNode = function() {
  return /** @type{?proto.shared.v1.GraphNode} */ (
    jspb.Message.getWrapperField(this, shared_graph_pb.GraphNode, 1));
};


/**
 * @param {?proto.shared.v1.GraphNode|undefined} value
 * @return {!proto.shared.v1.StructureChunk} returns this
*/
proto.shared.v1.StructureChunk.prototype.setNode = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.shared.v1.StructureChunk.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.shared.v1.StructureChunk} returns this
 */
proto.shared.v1.StructureChunk.prototype.clearNode = function() {
  return this.setNode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.shared.v1.StructureChunk.prototype.hasNode = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional GraphEdge edge = 2;
 * @return {?proto.shared.v1.GraphEdge}
 */
proto.shared.v1.StructureChunk.prototype.getEdge = function() {
  return /** @type{?proto.shared.v1.GraphEdge} */ (
    jspb.Message.getWrapperField(this, shared_graph_pb.GraphEdge, 2));
};


/**
 * @param {?proto.shared.v1.GraphEdge|undefined} value
 * @return {!proto.shared.v1.StructureChunk} returns this
*/
proto.shared.v1.StructureChunk.prototype.setEdge = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.shared.v1.StructureChunk.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.shared.v1.StructureChunk} returns this
 */
proto.shared.v1.StructureChunk.prototype.clearEdge = function() {
  return this.setEdge(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.shared.v1.StructureChunk.prototype.hasEdge = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string warning = 3;
 * @return {string}
 */
proto.shared.v1.StructureChunk.prototype.getWarning = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.shared.v1.StructureChunk} returns this
 */
proto.shared.v1.StructureChunk.prototype.setWarning = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.shared.v1.StructureChunk.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.shared.v1.StructureChunk} returns this
 */
proto.shared.v1.StructureChunk.prototype.clearWarning = function() {
  return jspb.Message.setOneofField(this, 3, proto.shared.v1.StructureChunk.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.shared.v1.StructureChunk.prototype.hasWarning = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional bool is_final = 4;
 * @return {boolean}
 */
proto.shared.v1.StructureChunk.prototype.getIsFinal = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.shared.v1.StructureChunk} returns this
 */
proto.shared.v1.StructureChunk.prototype.setIsFinal = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional double confidence = 5;
 * @return {number}
 */
proto.shared.v1.StructureChunk.prototype.getConfidence = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.shared.v1.StructureChunk} returns this
 */
proto.shared.v1.StructureChunk.prototype.setConfidence = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional ResponseMeta meta = 6;
 * @return {?proto.shared.v1.ResponseMeta}
 */
proto.shared.v1.StructureChunk.prototype.getMeta = function() {
  return /** @type{?proto.shared.v1.ResponseMeta} */ (
    jspb.Message.getWrapperField(this, shared_common_pb.ResponseMeta, 6));
};


/**
 * @param {?proto.shared.v1.ResponseMeta|undefined} value
 * @return {!proto.shared.v1.StructureChunk} returns this
*/
proto.shared.v1.StructureChunk.prototype.setMeta = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.shared.v1.StructureChunk} returns this
 */
proto.shared.v1.StructureChunk.prototype.clearMeta = function() {
  return this.setMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.shared.v1.StructureChunk.prototype.hasMeta = function() {
  return jspb.Message.getField(this, 6) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.shared.v1.AlgorithmSuggestionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.shared.v1.AlgorithmSuggestionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.shared.v1.AlgorithmSuggestionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.AlgorithmSuggestionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
context: (f = msg.getContext()) && shared_graph_pb.Graph.toObject(includeInstance, f),
goal: jspb.Message.getFieldWithDefault(msg, 2, ""),
module: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.shared.v1.AlgorithmSuggestionRequest}
 */
proto.shared.v1.AlgorithmSuggestionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.shared.v1.AlgorithmSuggestionRequest;
  return proto.shared.v1.AlgorithmSuggestionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.shared.v1.AlgorithmSuggestionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.shared.v1.AlgorithmSuggestionRequest}
 */
proto.shared.v1.AlgorithmSuggestionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new shared_graph_pb.Graph;
      reader.readMessage(value,shared_graph_pb.Graph.deserializeBinaryFromReader);
      msg.setContext(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setGoal(value);
      break;
    case 3:
      var value = /** @type {!proto.shared.v1.ModuleKind} */ (reader.readEnum());
      msg.setModule(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.shared.v1.AlgorithmSuggestionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.shared.v1.AlgorithmSuggestionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.shared.v1.AlgorithmSuggestionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.AlgorithmSuggestionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContext();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      shared_graph_pb.Graph.serializeBinaryToWriter
    );
  }
  f = message.getGoal();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getModule();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional Graph context = 1;
 * @return {?proto.shared.v1.Graph}
 */
proto.shared.v1.AlgorithmSuggestionRequest.prototype.getContext = function() {
  return /** @type{?proto.shared.v1.Graph} */ (
    jspb.Message.getWrapperField(this, shared_graph_pb.Graph, 1));
};


/**
 * @param {?proto.shared.v1.Graph|undefined} value
 * @return {!proto.shared.v1.AlgorithmSuggestionRequest} returns this
*/
proto.shared.v1.AlgorithmSuggestionRequest.prototype.setContext = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.shared.v1.AlgorithmSuggestionRequest} returns this
 */
proto.shared.v1.AlgorithmSuggestionRequest.prototype.clearContext = function() {
  return this.setContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.shared.v1.AlgorithmSuggestionRequest.prototype.hasContext = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string goal = 2;
 * @return {string}
 */
proto.shared.v1.AlgorithmSuggestionRequest.prototype.getGoal = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.shared.v1.AlgorithmSuggestionRequest} returns this
 */
proto.shared.v1.AlgorithmSuggestionRequest.prototype.setGoal = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional ModuleKind module = 3;
 * @return {!proto.shared.v1.ModuleKind}
 */
proto.shared.v1.AlgorithmSuggestionRequest.prototype.getModule = function() {
  return /** @type {!proto.shared.v1.ModuleKind} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.shared.v1.ModuleKind} value
 * @return {!proto.shared.v1.AlgorithmSuggestionRequest} returns this
 */
proto.shared.v1.AlgorithmSuggestionRequest.prototype.setModule = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.shared.v1.AlgorithmSuggestionResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.shared.v1.AlgorithmSuggestionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.shared.v1.AlgorithmSuggestionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.shared.v1.AlgorithmSuggestionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.AlgorithmSuggestionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
suggestionsList: jspb.Message.toObjectList(msg.getSuggestionsList(),
    proto.shared.v1.AlgorithmSuggestion.toObject, includeInstance),
meta: (f = msg.getMeta()) && shared_common_pb.ResponseMeta.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.shared.v1.AlgorithmSuggestionResponse}
 */
proto.shared.v1.AlgorithmSuggestionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.shared.v1.AlgorithmSuggestionResponse;
  return proto.shared.v1.AlgorithmSuggestionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.shared.v1.AlgorithmSuggestionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.shared.v1.AlgorithmSuggestionResponse}
 */
proto.shared.v1.AlgorithmSuggestionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.shared.v1.AlgorithmSuggestion;
      reader.readMessage(value,proto.shared.v1.AlgorithmSuggestion.deserializeBinaryFromReader);
      msg.addSuggestions(value);
      break;
    case 2:
      var value = new shared_common_pb.ResponseMeta;
      reader.readMessage(value,shared_common_pb.ResponseMeta.deserializeBinaryFromReader);
      msg.setMeta(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.shared.v1.AlgorithmSuggestionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.shared.v1.AlgorithmSuggestionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.shared.v1.AlgorithmSuggestionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.AlgorithmSuggestionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSuggestionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.shared.v1.AlgorithmSuggestion.serializeBinaryToWriter
    );
  }
  f = message.getMeta();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      shared_common_pb.ResponseMeta.serializeBinaryToWriter
    );
  }
};


/**
 * repeated AlgorithmSuggestion suggestions = 1;
 * @return {!Array<!proto.shared.v1.AlgorithmSuggestion>}
 */
proto.shared.v1.AlgorithmSuggestionResponse.prototype.getSuggestionsList = function() {
  return /** @type{!Array<!proto.shared.v1.AlgorithmSuggestion>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.shared.v1.AlgorithmSuggestion, 1));
};


/**
 * @param {!Array<!proto.shared.v1.AlgorithmSuggestion>} value
 * @return {!proto.shared.v1.AlgorithmSuggestionResponse} returns this
*/
proto.shared.v1.AlgorithmSuggestionResponse.prototype.setSuggestionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.shared.v1.AlgorithmSuggestion=} opt_value
 * @param {number=} opt_index
 * @return {!proto.shared.v1.AlgorithmSuggestion}
 */
proto.shared.v1.AlgorithmSuggestionResponse.prototype.addSuggestions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.shared.v1.AlgorithmSuggestion, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.shared.v1.AlgorithmSuggestionResponse} returns this
 */
proto.shared.v1.AlgorithmSuggestionResponse.prototype.clearSuggestionsList = function() {
  return this.setSuggestionsList([]);
};


/**
 * optional ResponseMeta meta = 2;
 * @return {?proto.shared.v1.ResponseMeta}
 */
proto.shared.v1.AlgorithmSuggestionResponse.prototype.getMeta = function() {
  return /** @type{?proto.shared.v1.ResponseMeta} */ (
    jspb.Message.getWrapperField(this, shared_common_pb.ResponseMeta, 2));
};


/**
 * @param {?proto.shared.v1.ResponseMeta|undefined} value
 * @return {!proto.shared.v1.AlgorithmSuggestionResponse} returns this
*/
proto.shared.v1.AlgorithmSuggestionResponse.prototype.setMeta = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.shared.v1.AlgorithmSuggestionResponse} returns this
 */
proto.shared.v1.AlgorithmSuggestionResponse.prototype.clearMeta = function() {
  return this.setMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.shared.v1.AlgorithmSuggestionResponse.prototype.hasMeta = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.shared.v1.AlgorithmSuggestion.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.shared.v1.AlgorithmSuggestion.prototype.toObject = function(opt_includeInstance) {
  return proto.shared.v1.AlgorithmSuggestion.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.shared.v1.AlgorithmSuggestion} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.AlgorithmSuggestion.toObject = function(includeInstance, msg) {
  var f, obj = {
algorithmId: jspb.Message.getFieldWithDefault(msg, 1, ""),
name: jspb.Message.getFieldWithDefault(msg, 2, ""),
rationale: jspb.Message.getFieldWithDefault(msg, 3, ""),
confidence: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
parametersList: jspb.Message.toObjectList(msg.getParametersList(),
    shared_common_pb.Property.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.shared.v1.AlgorithmSuggestion}
 */
proto.shared.v1.AlgorithmSuggestion.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.shared.v1.AlgorithmSuggestion;
  return proto.shared.v1.AlgorithmSuggestion.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.shared.v1.AlgorithmSuggestion} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.shared.v1.AlgorithmSuggestion}
 */
proto.shared.v1.AlgorithmSuggestion.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAlgorithmId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRationale(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setConfidence(value);
      break;
    case 5:
      var value = new shared_common_pb.Property;
      reader.readMessage(value,shared_common_pb.Property.deserializeBinaryFromReader);
      msg.addParameters(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.shared.v1.AlgorithmSuggestion.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.shared.v1.AlgorithmSuggestion.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.shared.v1.AlgorithmSuggestion} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.shared.v1.AlgorithmSuggestion.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAlgorithmId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRationale();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getConfidence();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getParametersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      shared_common_pb.Property.serializeBinaryToWriter
    );
  }
};


/**
 * optional string algorithm_id = 1;
 * @return {string}
 */
proto.shared.v1.AlgorithmSuggestion.prototype.getAlgorithmId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.shared.v1.AlgorithmSuggestion} returns this
 */
proto.shared.v1.AlgorithmSuggestion.prototype.setAlgorithmId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.shared.v1.AlgorithmSuggestion.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.shared.v1.AlgorithmSuggestion} returns this
 */
proto.shared.v1.AlgorithmSuggestion.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string rationale = 3;
 * @return {string}
 */
proto.shared.v1.AlgorithmSuggestion.prototype.getRationale = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.shared.v1.AlgorithmSuggestion} returns this
 */
proto.shared.v1.AlgorithmSuggestion.prototype.setRationale = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional double confidence = 4;
 * @return {number}
 */
proto.shared.v1.AlgorithmSuggestion.prototype.getConfidence = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.shared.v1.AlgorithmSuggestion} returns this
 */
proto.shared.v1.AlgorithmSuggestion.prototype.setConfidence = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * repeated Property parameters = 5;
 * @return {!Array<!proto.shared.v1.Property>}
 */
proto.shared.v1.AlgorithmSuggestion.prototype.getParametersList = function() {
  return /** @type{!Array<!proto.shared.v1.Property>} */ (
    jspb.Message.getRepeatedWrapperField(this, shared_common_pb.Property, 5));
};


/**
 * @param {!Array<!proto.shared.v1.Property>} value
 * @return {!proto.shared.v1.AlgorithmSuggestion} returns this
*/
proto.shared.v1.AlgorithmSuggestion.prototype.setParametersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.shared.v1.Property=} opt_value
 * @param {number=} opt_index
 * @return {!proto.shared.v1.Property}
 */
proto.shared.v1.AlgorithmSuggestion.prototype.addParameters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.shared.v1.Property, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.shared.v1.AlgorithmSuggestion} returns this
 */
proto.shared.v1.AlgorithmSuggestion.prototype.clearParametersList = function() {
  return this.setParametersList([]);
};


/**
 * @enum {number}
 */
proto.shared.v1.StructureTarget = {
  STRUCTURE_TARGET_UNSPECIFIED: 0,
  STRUCTURE_TARGET_CONCEPT: 1,
  STRUCTURE_TARGET_ENTITY: 2,
  STRUCTURE_TARGET_SCENARIO: 3,
  STRUCTURE_TARGET_ALGORITHM: 4
};

/**
 * @enum {number}
 */
proto.shared.v1.ModuleKind = {
  MK_UNSPECIFIED: 0,
  MK_GEOMETRY: 1,
  MK_REASONING: 2
};

goog.object.extend(exports, proto.shared.v1);
