/**
 * @fileoverview gRPC-Web generated client stub for shared.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: shared/llm.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as shared_llm_pb from '../shared/llm_pb'; // proto import: "shared/llm.proto"


export class LLMGatewayClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorStructureInput = new grpcWeb.MethodDescriptor(
    '/shared.v1.LLMGateway/StructureInput',
    grpcWeb.MethodType.UNARY,
    shared_llm_pb.StructureRequest,
    shared_llm_pb.StructureResponse,
    (request: shared_llm_pb.StructureRequest) => {
      return request.serializeBinary();
    },
    shared_llm_pb.StructureResponse.deserializeBinary
  );

  structureInput(
    request: shared_llm_pb.StructureRequest,
    metadata?: grpcWeb.Metadata | null): Promise<shared_llm_pb.StructureResponse>;

  structureInput(
    request: shared_llm_pb.StructureRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: shared_llm_pb.StructureResponse) => void): grpcWeb.ClientReadableStream<shared_llm_pb.StructureResponse>;

  structureInput(
    request: shared_llm_pb.StructureRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: shared_llm_pb.StructureResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/shared.v1.LLMGateway/StructureInput',
        request,
        metadata || {},
        this.methodDescriptorStructureInput,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/shared.v1.LLMGateway/StructureInput',
    request,
    metadata || {},
    this.methodDescriptorStructureInput);
  }

  methodDescriptorStructureInputStream = new grpcWeb.MethodDescriptor(
    '/shared.v1.LLMGateway/StructureInputStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    shared_llm_pb.StructureRequest,
    shared_llm_pb.StructureChunk,
    (request: shared_llm_pb.StructureRequest) => {
      return request.serializeBinary();
    },
    shared_llm_pb.StructureChunk.deserializeBinary
  );

  structureInputStream(
    request: shared_llm_pb.StructureRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<shared_llm_pb.StructureChunk> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/shared.v1.LLMGateway/StructureInputStream',
      request,
      metadata || {},
      this.methodDescriptorStructureInputStream);
  }

  methodDescriptorSuggestAlgorithms = new grpcWeb.MethodDescriptor(
    '/shared.v1.LLMGateway/SuggestAlgorithms',
    grpcWeb.MethodType.UNARY,
    shared_llm_pb.AlgorithmSuggestionRequest,
    shared_llm_pb.AlgorithmSuggestionResponse,
    (request: shared_llm_pb.AlgorithmSuggestionRequest) => {
      return request.serializeBinary();
    },
    shared_llm_pb.AlgorithmSuggestionResponse.deserializeBinary
  );

  suggestAlgorithms(
    request: shared_llm_pb.AlgorithmSuggestionRequest,
    metadata?: grpcWeb.Metadata | null): Promise<shared_llm_pb.AlgorithmSuggestionResponse>;

  suggestAlgorithms(
    request: shared_llm_pb.AlgorithmSuggestionRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: shared_llm_pb.AlgorithmSuggestionResponse) => void): grpcWeb.ClientReadableStream<shared_llm_pb.AlgorithmSuggestionResponse>;

  suggestAlgorithms(
    request: shared_llm_pb.AlgorithmSuggestionRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: shared_llm_pb.AlgorithmSuggestionResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/shared.v1.LLMGateway/SuggestAlgorithms',
        request,
        metadata || {},
        this.methodDescriptorSuggestAlgorithms,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/shared.v1.LLMGateway/SuggestAlgorithms',
    request,
    metadata || {},
    this.methodDescriptorSuggestAlgorithms);
  }

}

