/**
 * @fileoverview gRPC-Web generated client stub for geometry.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: geometry/geometry.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as geometry_geometry_pb from '../geometry/geometry_pb'; // proto import: "geometry/geometry.proto"


export class GeometryServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorStreamGeometryResult = new grpcWeb.MethodDescriptor(
    '/geometry.v1.GeometryService/StreamGeometryResult',
    grpcWeb.MethodType.SERVER_STREAMING,
    geometry_geometry_pb.GeometryResultRequest,
    geometry_geometry_pb.GeometryResultChunk,
    (request: geometry_geometry_pb.GeometryResultRequest) => {
      return request.serializeBinary();
    },
    geometry_geometry_pb.GeometryResultChunk.deserializeBinary
  );

  streamGeometryResult(
    request: geometry_geometry_pb.GeometryResultRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<geometry_geometry_pb.GeometryResultChunk> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/geometry.v1.GeometryService/StreamGeometryResult',
      request,
      metadata || {},
      this.methodDescriptorStreamGeometryResult);
  }

  methodDescriptorSuggestGeometryAlgorithms = new grpcWeb.MethodDescriptor(
    '/geometry.v1.GeometryService/SuggestGeometryAlgorithms',
    grpcWeb.MethodType.UNARY,
    geometry_geometry_pb.SuggestGeometryAlgorithmsRequest,
    geometry_geometry_pb.SuggestGeometryAlgorithmsResponse,
    (request: geometry_geometry_pb.SuggestGeometryAlgorithmsRequest) => {
      return request.serializeBinary();
    },
    geometry_geometry_pb.SuggestGeometryAlgorithmsResponse.deserializeBinary
  );

  suggestGeometryAlgorithms(
    request: geometry_geometry_pb.SuggestGeometryAlgorithmsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<geometry_geometry_pb.SuggestGeometryAlgorithmsResponse>;

  suggestGeometryAlgorithms(
    request: geometry_geometry_pb.SuggestGeometryAlgorithmsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: geometry_geometry_pb.SuggestGeometryAlgorithmsResponse) => void): grpcWeb.ClientReadableStream<geometry_geometry_pb.SuggestGeometryAlgorithmsResponse>;

  suggestGeometryAlgorithms(
    request: geometry_geometry_pb.SuggestGeometryAlgorithmsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: geometry_geometry_pb.SuggestGeometryAlgorithmsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/geometry.v1.GeometryService/SuggestGeometryAlgorithms',
        request,
        metadata || {},
        this.methodDescriptorSuggestGeometryAlgorithms,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/geometry.v1.GeometryService/SuggestGeometryAlgorithms',
    request,
    metadata || {},
    this.methodDescriptorSuggestGeometryAlgorithms);
  }

  methodDescriptorExecutePipeline = new grpcWeb.MethodDescriptor(
    '/geometry.v1.GeometryService/ExecutePipeline',
    grpcWeb.MethodType.SERVER_STREAMING,
    geometry_geometry_pb.ExecutePipelineRequest,
    geometry_geometry_pb.PipelineResultChunk,
    (request: geometry_geometry_pb.ExecutePipelineRequest) => {
      return request.serializeBinary();
    },
    geometry_geometry_pb.PipelineResultChunk.deserializeBinary
  );

  executePipeline(
    request: geometry_geometry_pb.ExecutePipelineRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<geometry_geometry_pb.PipelineResultChunk> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/geometry.v1.GeometryService/ExecutePipeline',
      request,
      metadata || {},
      this.methodDescriptorExecutePipeline);
  }

}

