// source: reasoning/reasoning.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var shared_common_pb = require('../shared/common_pb.js');
goog.object.extend(proto, shared_common_pb);
var shared_graph_pb = require('../shared/graph_pb.js');
goog.object.extend(proto, shared_graph_pb);
goog.exportSymbol('proto.reasoning.v1.AnalysisKind', null, global);
goog.exportSymbol('proto.reasoning.v1.AnalyzeGraphRequest', null, global);
goog.exportSymbol('proto.reasoning.v1.AnalyzeGraphResponse', null, global);
goog.exportSymbol('proto.reasoning.v1.BuildConceptGraphRequest', null, global);
goog.exportSymbol('proto.reasoning.v1.BuildConceptGraphResponse', null, global);
goog.exportSymbol('proto.reasoning.v1.CycleResult', null, global);
goog.exportSymbol('proto.reasoning.v1.NodeMetric', null, global);
goog.exportSymbol('proto.reasoning.v1.NodePerturbation', null, global);
goog.exportSymbol('proto.reasoning.v1.NodeState', null, global);
goog.exportSymbol('proto.reasoning.v1.PerturbationDirection', null, global);
goog.exportSymbol('proto.reasoning.v1.RunScenarioRequest', null, global);
goog.exportSymbol('proto.reasoning.v1.RunScenarioResponse', null, global);
goog.exportSymbol('proto.reasoning.v1.ScenarioConfig', null, global);
goog.exportSymbol('proto.reasoning.v1.ScenarioPropagationChunk', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.reasoning.v1.BuildConceptGraphRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.reasoning.v1.BuildConceptGraphRequest.repeatedFields_, null);
};
goog.inherits(proto.reasoning.v1.BuildConceptGraphRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.reasoning.v1.BuildConceptGraphRequest.displayName = 'proto.reasoning.v1.BuildConceptGraphRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.reasoning.v1.BuildConceptGraphResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.reasoning.v1.BuildConceptGraphResponse.repeatedFields_, null);
};
goog.inherits(proto.reasoning.v1.BuildConceptGraphResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.reasoning.v1.BuildConceptGraphResponse.displayName = 'proto.reasoning.v1.BuildConceptGraphResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.reasoning.v1.NodePerturbation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.reasoning.v1.NodePerturbation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.reasoning.v1.NodePerturbation.displayName = 'proto.reasoning.v1.NodePerturbation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.reasoning.v1.RunScenarioRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.reasoning.v1.RunScenarioRequest.repeatedFields_, null);
};
goog.inherits(proto.reasoning.v1.RunScenarioRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.reasoning.v1.RunScenarioRequest.displayName = 'proto.reasoning.v1.RunScenarioRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.reasoning.v1.ScenarioConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.reasoning.v1.ScenarioConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.reasoning.v1.ScenarioConfig.displayName = 'proto.reasoning.v1.ScenarioConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.reasoning.v1.NodeState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.reasoning.v1.NodeState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.reasoning.v1.NodeState.displayName = 'proto.reasoning.v1.NodeState';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.reasoning.v1.RunScenarioResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.reasoning.v1.RunScenarioResponse.repeatedFields_, null);
};
goog.inherits(proto.reasoning.v1.RunScenarioResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.reasoning.v1.RunScenarioResponse.displayName = 'proto.reasoning.v1.RunScenarioResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.reasoning.v1.ScenarioPropagationChunk = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.reasoning.v1.ScenarioPropagationChunk.repeatedFields_, null);
};
goog.inherits(proto.reasoning.v1.ScenarioPropagationChunk, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.reasoning.v1.ScenarioPropagationChunk.displayName = 'proto.reasoning.v1.ScenarioPropagationChunk';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.reasoning.v1.AnalyzeGraphRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.reasoning.v1.AnalyzeGraphRequest.repeatedFields_, null);
};
goog.inherits(proto.reasoning.v1.AnalyzeGraphRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.reasoning.v1.AnalyzeGraphRequest.displayName = 'proto.reasoning.v1.AnalyzeGraphRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.reasoning.v1.NodeMetric = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.reasoning.v1.NodeMetric, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.reasoning.v1.NodeMetric.displayName = 'proto.reasoning.v1.NodeMetric';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.reasoning.v1.CycleResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.reasoning.v1.CycleResult.repeatedFields_, null);
};
goog.inherits(proto.reasoning.v1.CycleResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.reasoning.v1.CycleResult.displayName = 'proto.reasoning.v1.CycleResult';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.reasoning.v1.AnalyzeGraphResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.reasoning.v1.AnalyzeGraphResponse.repeatedFields_, null);
};
goog.inherits(proto.reasoning.v1.AnalyzeGraphResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.reasoning.v1.AnalyzeGraphResponse.displayName = 'proto.reasoning.v1.AnalyzeGraphResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.reasoning.v1.BuildConceptGraphRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.reasoning.v1.BuildConceptGraphRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.reasoning.v1.BuildConceptGraphRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.reasoning.v1.BuildConceptGraphRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.BuildConceptGraphRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
rawInput: jspb.Message.getFieldWithDefault(msg, 1, ""),
sessionId: jspb.Message.getFieldWithDefault(msg, 2, ""),
hintsList: jspb.Message.toObjectList(msg.getHintsList(),
    shared_common_pb.Property.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.reasoning.v1.BuildConceptGraphRequest}
 */
proto.reasoning.v1.BuildConceptGraphRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.reasoning.v1.BuildConceptGraphRequest;
  return proto.reasoning.v1.BuildConceptGraphRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.reasoning.v1.BuildConceptGraphRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.reasoning.v1.BuildConceptGraphRequest}
 */
proto.reasoning.v1.BuildConceptGraphRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRawInput(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessionId(value);
      break;
    case 3:
      var value = new shared_common_pb.Property;
      reader.readMessage(value,shared_common_pb.Property.deserializeBinaryFromReader);
      msg.addHints(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.reasoning.v1.BuildConceptGraphRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.reasoning.v1.BuildConceptGraphRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.reasoning.v1.BuildConceptGraphRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.BuildConceptGraphRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRawInput();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSessionId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getHintsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      shared_common_pb.Property.serializeBinaryToWriter
    );
  }
};


/**
 * optional string raw_input = 1;
 * @return {string}
 */
proto.reasoning.v1.BuildConceptGraphRequest.prototype.getRawInput = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.reasoning.v1.BuildConceptGraphRequest} returns this
 */
proto.reasoning.v1.BuildConceptGraphRequest.prototype.setRawInput = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string session_id = 2;
 * @return {string}
 */
proto.reasoning.v1.BuildConceptGraphRequest.prototype.getSessionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.reasoning.v1.BuildConceptGraphRequest} returns this
 */
proto.reasoning.v1.BuildConceptGraphRequest.prototype.setSessionId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated shared.v1.Property hints = 3;
 * @return {!Array<!proto.shared.v1.Property>}
 */
proto.reasoning.v1.BuildConceptGraphRequest.prototype.getHintsList = function() {
  return /** @type{!Array<!proto.shared.v1.Property>} */ (
    jspb.Message.getRepeatedWrapperField(this, shared_common_pb.Property, 3));
};


/**
 * @param {!Array<!proto.shared.v1.Property>} value
 * @return {!proto.reasoning.v1.BuildConceptGraphRequest} returns this
*/
proto.reasoning.v1.BuildConceptGraphRequest.prototype.setHintsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.shared.v1.Property=} opt_value
 * @param {number=} opt_index
 * @return {!proto.shared.v1.Property}
 */
proto.reasoning.v1.BuildConceptGraphRequest.prototype.addHints = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.shared.v1.Property, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reasoning.v1.BuildConceptGraphRequest} returns this
 */
proto.reasoning.v1.BuildConceptGraphRequest.prototype.clearHintsList = function() {
  return this.setHintsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.reasoning.v1.BuildConceptGraphResponse.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.reasoning.v1.BuildConceptGraphResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.reasoning.v1.BuildConceptGraphResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.reasoning.v1.BuildConceptGraphResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.BuildConceptGraphResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
graph: (f = msg.getGraph()) && shared_graph_pb.Graph.toObject(includeInstance, f),
confidence: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
warningsList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
meta: (f = msg.getMeta()) && shared_common_pb.ResponseMeta.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.reasoning.v1.BuildConceptGraphResponse}
 */
proto.reasoning.v1.BuildConceptGraphResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.reasoning.v1.BuildConceptGraphResponse;
  return proto.reasoning.v1.BuildConceptGraphResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.reasoning.v1.BuildConceptGraphResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.reasoning.v1.BuildConceptGraphResponse}
 */
proto.reasoning.v1.BuildConceptGraphResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new shared_graph_pb.Graph;
      reader.readMessage(value,shared_graph_pb.Graph.deserializeBinaryFromReader);
      msg.setGraph(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setConfidence(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addWarnings(value);
      break;
    case 4:
      var value = new shared_common_pb.ResponseMeta;
      reader.readMessage(value,shared_common_pb.ResponseMeta.deserializeBinaryFromReader);
      msg.setMeta(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.reasoning.v1.BuildConceptGraphResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.reasoning.v1.BuildConceptGraphResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.reasoning.v1.BuildConceptGraphResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.BuildConceptGraphResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGraph();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      shared_graph_pb.Graph.serializeBinaryToWriter
    );
  }
  f = message.getConfidence();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getWarningsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getMeta();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      shared_common_pb.ResponseMeta.serializeBinaryToWriter
    );
  }
};


/**
 * optional shared.v1.Graph graph = 1;
 * @return {?proto.shared.v1.Graph}
 */
proto.reasoning.v1.BuildConceptGraphResponse.prototype.getGraph = function() {
  return /** @type{?proto.shared.v1.Graph} */ (
    jspb.Message.getWrapperField(this, shared_graph_pb.Graph, 1));
};


/**
 * @param {?proto.shared.v1.Graph|undefined} value
 * @return {!proto.reasoning.v1.BuildConceptGraphResponse} returns this
*/
proto.reasoning.v1.BuildConceptGraphResponse.prototype.setGraph = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reasoning.v1.BuildConceptGraphResponse} returns this
 */
proto.reasoning.v1.BuildConceptGraphResponse.prototype.clearGraph = function() {
  return this.setGraph(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reasoning.v1.BuildConceptGraphResponse.prototype.hasGraph = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional double confidence = 2;
 * @return {number}
 */
proto.reasoning.v1.BuildConceptGraphResponse.prototype.getConfidence = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.reasoning.v1.BuildConceptGraphResponse} returns this
 */
proto.reasoning.v1.BuildConceptGraphResponse.prototype.setConfidence = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * repeated string warnings = 3;
 * @return {!Array<string>}
 */
proto.reasoning.v1.BuildConceptGraphResponse.prototype.getWarningsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.reasoning.v1.BuildConceptGraphResponse} returns this
 */
proto.reasoning.v1.BuildConceptGraphResponse.prototype.setWarningsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.reasoning.v1.BuildConceptGraphResponse} returns this
 */
proto.reasoning.v1.BuildConceptGraphResponse.prototype.addWarnings = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reasoning.v1.BuildConceptGraphResponse} returns this
 */
proto.reasoning.v1.BuildConceptGraphResponse.prototype.clearWarningsList = function() {
  return this.setWarningsList([]);
};


/**
 * optional shared.v1.ResponseMeta meta = 4;
 * @return {?proto.shared.v1.ResponseMeta}
 */
proto.reasoning.v1.BuildConceptGraphResponse.prototype.getMeta = function() {
  return /** @type{?proto.shared.v1.ResponseMeta} */ (
    jspb.Message.getWrapperField(this, shared_common_pb.ResponseMeta, 4));
};


/**
 * @param {?proto.shared.v1.ResponseMeta|undefined} value
 * @return {!proto.reasoning.v1.BuildConceptGraphResponse} returns this
*/
proto.reasoning.v1.BuildConceptGraphResponse.prototype.setMeta = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reasoning.v1.BuildConceptGraphResponse} returns this
 */
proto.reasoning.v1.BuildConceptGraphResponse.prototype.clearMeta = function() {
  return this.setMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reasoning.v1.BuildConceptGraphResponse.prototype.hasMeta = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.reasoning.v1.NodePerturbation.prototype.toObject = function(opt_includeInstance) {
  return proto.reasoning.v1.NodePerturbation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.reasoning.v1.NodePerturbation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.NodePerturbation.toObject = function(includeInstance, msg) {
  var f, obj = {
nodeId: jspb.Message.getFieldWithDefault(msg, 1, ""),
direction: jspb.Message.getFieldWithDefault(msg, 2, 0),
magnitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
initialValue: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.reasoning.v1.NodePerturbation}
 */
proto.reasoning.v1.NodePerturbation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.reasoning.v1.NodePerturbation;
  return proto.reasoning.v1.NodePerturbation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.reasoning.v1.NodePerturbation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.reasoning.v1.NodePerturbation}
 */
proto.reasoning.v1.NodePerturbation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNodeId(value);
      break;
    case 2:
      var value = /** @type {!proto.reasoning.v1.PerturbationDirection} */ (reader.readEnum());
      msg.setDirection(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMagnitude(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setInitialValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.reasoning.v1.NodePerturbation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.reasoning.v1.NodePerturbation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.reasoning.v1.NodePerturbation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.NodePerturbation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNodeId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDirection();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getMagnitude();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getInitialValue();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
};


/**
 * optional string node_id = 1;
 * @return {string}
 */
proto.reasoning.v1.NodePerturbation.prototype.getNodeId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.reasoning.v1.NodePerturbation} returns this
 */
proto.reasoning.v1.NodePerturbation.prototype.setNodeId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional PerturbationDirection direction = 2;
 * @return {!proto.reasoning.v1.PerturbationDirection}
 */
proto.reasoning.v1.NodePerturbation.prototype.getDirection = function() {
  return /** @type {!proto.reasoning.v1.PerturbationDirection} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.reasoning.v1.PerturbationDirection} value
 * @return {!proto.reasoning.v1.NodePerturbation} returns this
 */
proto.reasoning.v1.NodePerturbation.prototype.setDirection = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional double magnitude = 3;
 * @return {number}
 */
proto.reasoning.v1.NodePerturbation.prototype.getMagnitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.reasoning.v1.NodePerturbation} returns this
 */
proto.reasoning.v1.NodePerturbation.prototype.setMagnitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double initial_value = 4;
 * @return {number}
 */
proto.reasoning.v1.NodePerturbation.prototype.getInitialValue = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.reasoning.v1.NodePerturbation} returns this
 */
proto.reasoning.v1.NodePerturbation.prototype.setInitialValue = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.reasoning.v1.RunScenarioRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.reasoning.v1.RunScenarioRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.reasoning.v1.RunScenarioRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.reasoning.v1.RunScenarioRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.RunScenarioRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
baseGraph: (f = msg.getBaseGraph()) && shared_graph_pb.Graph.toObject(includeInstance, f),
perturbationsList: jspb.Message.toObjectList(msg.getPerturbationsList(),
    proto.reasoning.v1.NodePerturbation.toObject, includeInstance),
sessionId: jspb.Message.getFieldWithDefault(msg, 3, ""),
config: (f = msg.getConfig()) && proto.reasoning.v1.ScenarioConfig.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.reasoning.v1.RunScenarioRequest}
 */
proto.reasoning.v1.RunScenarioRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.reasoning.v1.RunScenarioRequest;
  return proto.reasoning.v1.RunScenarioRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.reasoning.v1.RunScenarioRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.reasoning.v1.RunScenarioRequest}
 */
proto.reasoning.v1.RunScenarioRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new shared_graph_pb.Graph;
      reader.readMessage(value,shared_graph_pb.Graph.deserializeBinaryFromReader);
      msg.setBaseGraph(value);
      break;
    case 2:
      var value = new proto.reasoning.v1.NodePerturbation;
      reader.readMessage(value,proto.reasoning.v1.NodePerturbation.deserializeBinaryFromReader);
      msg.addPerturbations(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessionId(value);
      break;
    case 4:
      var value = new proto.reasoning.v1.ScenarioConfig;
      reader.readMessage(value,proto.reasoning.v1.ScenarioConfig.deserializeBinaryFromReader);
      msg.setConfig(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.reasoning.v1.RunScenarioRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.reasoning.v1.RunScenarioRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.reasoning.v1.RunScenarioRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.RunScenarioRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBaseGraph();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      shared_graph_pb.Graph.serializeBinaryToWriter
    );
  }
  f = message.getPerturbationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.reasoning.v1.NodePerturbation.serializeBinaryToWriter
    );
  }
  f = message.getSessionId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getConfig();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.reasoning.v1.ScenarioConfig.serializeBinaryToWriter
    );
  }
};


/**
 * optional shared.v1.Graph base_graph = 1;
 * @return {?proto.shared.v1.Graph}
 */
proto.reasoning.v1.RunScenarioRequest.prototype.getBaseGraph = function() {
  return /** @type{?proto.shared.v1.Graph} */ (
    jspb.Message.getWrapperField(this, shared_graph_pb.Graph, 1));
};


/**
 * @param {?proto.shared.v1.Graph|undefined} value
 * @return {!proto.reasoning.v1.RunScenarioRequest} returns this
*/
proto.reasoning.v1.RunScenarioRequest.prototype.setBaseGraph = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reasoning.v1.RunScenarioRequest} returns this
 */
proto.reasoning.v1.RunScenarioRequest.prototype.clearBaseGraph = function() {
  return this.setBaseGraph(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reasoning.v1.RunScenarioRequest.prototype.hasBaseGraph = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated NodePerturbation perturbations = 2;
 * @return {!Array<!proto.reasoning.v1.NodePerturbation>}
 */
proto.reasoning.v1.RunScenarioRequest.prototype.getPerturbationsList = function() {
  return /** @type{!Array<!proto.reasoning.v1.NodePerturbation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.reasoning.v1.NodePerturbation, 2));
};


/**
 * @param {!Array<!proto.reasoning.v1.NodePerturbation>} value
 * @return {!proto.reasoning.v1.RunScenarioRequest} returns this
*/
proto.reasoning.v1.RunScenarioRequest.prototype.setPerturbationsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.reasoning.v1.NodePerturbation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.reasoning.v1.NodePerturbation}
 */
proto.reasoning.v1.RunScenarioRequest.prototype.addPerturbations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.reasoning.v1.NodePerturbation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reasoning.v1.RunScenarioRequest} returns this
 */
proto.reasoning.v1.RunScenarioRequest.prototype.clearPerturbationsList = function() {
  return this.setPerturbationsList([]);
};


/**
 * optional string session_id = 3;
 * @return {string}
 */
proto.reasoning.v1.RunScenarioRequest.prototype.getSessionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.reasoning.v1.RunScenarioRequest} returns this
 */
proto.reasoning.v1.RunScenarioRequest.prototype.setSessionId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional ScenarioConfig config = 4;
 * @return {?proto.reasoning.v1.ScenarioConfig}
 */
proto.reasoning.v1.RunScenarioRequest.prototype.getConfig = function() {
  return /** @type{?proto.reasoning.v1.ScenarioConfig} */ (
    jspb.Message.getWrapperField(this, proto.reasoning.v1.ScenarioConfig, 4));
};


/**
 * @param {?proto.reasoning.v1.ScenarioConfig|undefined} value
 * @return {!proto.reasoning.v1.RunScenarioRequest} returns this
*/
proto.reasoning.v1.RunScenarioRequest.prototype.setConfig = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reasoning.v1.RunScenarioRequest} returns this
 */
proto.reasoning.v1.RunScenarioRequest.prototype.clearConfig = function() {
  return this.setConfig(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reasoning.v1.RunScenarioRequest.prototype.hasConfig = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.reasoning.v1.ScenarioConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.reasoning.v1.ScenarioConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.reasoning.v1.ScenarioConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.ScenarioConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
maxIterations: jspb.Message.getFieldWithDefault(msg, 1, 0),
convergenceDelta: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
detectCycles: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.reasoning.v1.ScenarioConfig}
 */
proto.reasoning.v1.ScenarioConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.reasoning.v1.ScenarioConfig;
  return proto.reasoning.v1.ScenarioConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.reasoning.v1.ScenarioConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.reasoning.v1.ScenarioConfig}
 */
proto.reasoning.v1.ScenarioConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMaxIterations(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setConvergenceDelta(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDetectCycles(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.reasoning.v1.ScenarioConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.reasoning.v1.ScenarioConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.reasoning.v1.ScenarioConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.ScenarioConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMaxIterations();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getConvergenceDelta();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getDetectCycles();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional uint32 max_iterations = 1;
 * @return {number}
 */
proto.reasoning.v1.ScenarioConfig.prototype.getMaxIterations = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.reasoning.v1.ScenarioConfig} returns this
 */
proto.reasoning.v1.ScenarioConfig.prototype.setMaxIterations = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional double convergence_delta = 2;
 * @return {number}
 */
proto.reasoning.v1.ScenarioConfig.prototype.getConvergenceDelta = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.reasoning.v1.ScenarioConfig} returns this
 */
proto.reasoning.v1.ScenarioConfig.prototype.setConvergenceDelta = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional bool detect_cycles = 3;
 * @return {boolean}
 */
proto.reasoning.v1.ScenarioConfig.prototype.getDetectCycles = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.reasoning.v1.ScenarioConfig} returns this
 */
proto.reasoning.v1.ScenarioConfig.prototype.setDetectCycles = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.reasoning.v1.NodeState.prototype.toObject = function(opt_includeInstance) {
  return proto.reasoning.v1.NodeState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.reasoning.v1.NodeState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.NodeState.toObject = function(includeInstance, msg) {
  var f, obj = {
nodeId: jspb.Message.getFieldWithDefault(msg, 1, ""),
value: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
delta: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
isPerturbed: jspb.Message.getBooleanFieldWithDefault(msg, 4, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.reasoning.v1.NodeState}
 */
proto.reasoning.v1.NodeState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.reasoning.v1.NodeState;
  return proto.reasoning.v1.NodeState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.reasoning.v1.NodeState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.reasoning.v1.NodeState}
 */
proto.reasoning.v1.NodeState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNodeId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setValue(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setDelta(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsPerturbed(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.reasoning.v1.NodeState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.reasoning.v1.NodeState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.reasoning.v1.NodeState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.NodeState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNodeId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getValue();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getDelta();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getIsPerturbed();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
};


/**
 * optional string node_id = 1;
 * @return {string}
 */
proto.reasoning.v1.NodeState.prototype.getNodeId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.reasoning.v1.NodeState} returns this
 */
proto.reasoning.v1.NodeState.prototype.setNodeId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional double value = 2;
 * @return {number}
 */
proto.reasoning.v1.NodeState.prototype.getValue = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.reasoning.v1.NodeState} returns this
 */
proto.reasoning.v1.NodeState.prototype.setValue = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double delta = 3;
 * @return {number}
 */
proto.reasoning.v1.NodeState.prototype.getDelta = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.reasoning.v1.NodeState} returns this
 */
proto.reasoning.v1.NodeState.prototype.setDelta = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional bool is_perturbed = 4;
 * @return {boolean}
 */
proto.reasoning.v1.NodeState.prototype.getIsPerturbed = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.reasoning.v1.NodeState} returns this
 */
proto.reasoning.v1.NodeState.prototype.setIsPerturbed = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.reasoning.v1.RunScenarioResponse.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.reasoning.v1.RunScenarioResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.reasoning.v1.RunScenarioResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.reasoning.v1.RunScenarioResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.RunScenarioResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
nodeStatesList: jspb.Message.toObjectList(msg.getNodeStatesList(),
    proto.reasoning.v1.NodeState.toObject, includeInstance),
warningsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
iterations: jspb.Message.getFieldWithDefault(msg, 3, 0),
converged: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
meta: (f = msg.getMeta()) && shared_common_pb.ResponseMeta.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.reasoning.v1.RunScenarioResponse}
 */
proto.reasoning.v1.RunScenarioResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.reasoning.v1.RunScenarioResponse;
  return proto.reasoning.v1.RunScenarioResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.reasoning.v1.RunScenarioResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.reasoning.v1.RunScenarioResponse}
 */
proto.reasoning.v1.RunScenarioResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.reasoning.v1.NodeState;
      reader.readMessage(value,proto.reasoning.v1.NodeState.deserializeBinaryFromReader);
      msg.addNodeStates(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addWarnings(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setIterations(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setConverged(value);
      break;
    case 5:
      var value = new shared_common_pb.ResponseMeta;
      reader.readMessage(value,shared_common_pb.ResponseMeta.deserializeBinaryFromReader);
      msg.setMeta(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.reasoning.v1.RunScenarioResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.reasoning.v1.RunScenarioResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.reasoning.v1.RunScenarioResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.RunScenarioResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNodeStatesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.reasoning.v1.NodeState.serializeBinaryToWriter
    );
  }
  f = message.getWarningsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getIterations();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getConverged();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getMeta();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      shared_common_pb.ResponseMeta.serializeBinaryToWriter
    );
  }
};


/**
 * repeated NodeState node_states = 1;
 * @return {!Array<!proto.reasoning.v1.NodeState>}
 */
proto.reasoning.v1.RunScenarioResponse.prototype.getNodeStatesList = function() {
  return /** @type{!Array<!proto.reasoning.v1.NodeState>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.reasoning.v1.NodeState, 1));
};


/**
 * @param {!Array<!proto.reasoning.v1.NodeState>} value
 * @return {!proto.reasoning.v1.RunScenarioResponse} returns this
*/
proto.reasoning.v1.RunScenarioResponse.prototype.setNodeStatesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.reasoning.v1.NodeState=} opt_value
 * @param {number=} opt_index
 * @return {!proto.reasoning.v1.NodeState}
 */
proto.reasoning.v1.RunScenarioResponse.prototype.addNodeStates = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.reasoning.v1.NodeState, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reasoning.v1.RunScenarioResponse} returns this
 */
proto.reasoning.v1.RunScenarioResponse.prototype.clearNodeStatesList = function() {
  return this.setNodeStatesList([]);
};


/**
 * repeated string warnings = 2;
 * @return {!Array<string>}
 */
proto.reasoning.v1.RunScenarioResponse.prototype.getWarningsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.reasoning.v1.RunScenarioResponse} returns this
 */
proto.reasoning.v1.RunScenarioResponse.prototype.setWarningsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.reasoning.v1.RunScenarioResponse} returns this
 */
proto.reasoning.v1.RunScenarioResponse.prototype.addWarnings = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reasoning.v1.RunScenarioResponse} returns this
 */
proto.reasoning.v1.RunScenarioResponse.prototype.clearWarningsList = function() {
  return this.setWarningsList([]);
};


/**
 * optional uint32 iterations = 3;
 * @return {number}
 */
proto.reasoning.v1.RunScenarioResponse.prototype.getIterations = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.reasoning.v1.RunScenarioResponse} returns this
 */
proto.reasoning.v1.RunScenarioResponse.prototype.setIterations = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional bool converged = 4;
 * @return {boolean}
 */
proto.reasoning.v1.RunScenarioResponse.prototype.getConverged = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.reasoning.v1.RunScenarioResponse} returns this
 */
proto.reasoning.v1.RunScenarioResponse.prototype.setConverged = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional shared.v1.ResponseMeta meta = 5;
 * @return {?proto.shared.v1.ResponseMeta}
 */
proto.reasoning.v1.RunScenarioResponse.prototype.getMeta = function() {
  return /** @type{?proto.shared.v1.ResponseMeta} */ (
    jspb.Message.getWrapperField(this, shared_common_pb.ResponseMeta, 5));
};


/**
 * @param {?proto.shared.v1.ResponseMeta|undefined} value
 * @return {!proto.reasoning.v1.RunScenarioResponse} returns this
*/
proto.reasoning.v1.RunScenarioResponse.prototype.setMeta = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reasoning.v1.RunScenarioResponse} returns this
 */
proto.reasoning.v1.RunScenarioResponse.prototype.clearMeta = function() {
  return this.setMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reasoning.v1.RunScenarioResponse.prototype.hasMeta = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.reasoning.v1.ScenarioPropagationChunk.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.reasoning.v1.ScenarioPropagationChunk.prototype.toObject = function(opt_includeInstance) {
  return proto.reasoning.v1.ScenarioPropagationChunk.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.reasoning.v1.ScenarioPropagationChunk} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.ScenarioPropagationChunk.toObject = function(includeInstance, msg) {
  var f, obj = {
nodeStatesList: jspb.Message.toObjectList(msg.getNodeStatesList(),
    proto.reasoning.v1.NodeState.toObject, includeInstance),
iteration: jspb.Message.getFieldWithDefault(msg, 2, 0),
isFinal: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
converged: jspb.Message.getBooleanFieldWithDefault(msg, 4, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.reasoning.v1.ScenarioPropagationChunk}
 */
proto.reasoning.v1.ScenarioPropagationChunk.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.reasoning.v1.ScenarioPropagationChunk;
  return proto.reasoning.v1.ScenarioPropagationChunk.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.reasoning.v1.ScenarioPropagationChunk} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.reasoning.v1.ScenarioPropagationChunk}
 */
proto.reasoning.v1.ScenarioPropagationChunk.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.reasoning.v1.NodeState;
      reader.readMessage(value,proto.reasoning.v1.NodeState.deserializeBinaryFromReader);
      msg.addNodeStates(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setIteration(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsFinal(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setConverged(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.reasoning.v1.ScenarioPropagationChunk.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.reasoning.v1.ScenarioPropagationChunk.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.reasoning.v1.ScenarioPropagationChunk} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.ScenarioPropagationChunk.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNodeStatesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.reasoning.v1.NodeState.serializeBinaryToWriter
    );
  }
  f = message.getIteration();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getIsFinal();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getConverged();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
};


/**
 * repeated NodeState node_states = 1;
 * @return {!Array<!proto.reasoning.v1.NodeState>}
 */
proto.reasoning.v1.ScenarioPropagationChunk.prototype.getNodeStatesList = function() {
  return /** @type{!Array<!proto.reasoning.v1.NodeState>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.reasoning.v1.NodeState, 1));
};


/**
 * @param {!Array<!proto.reasoning.v1.NodeState>} value
 * @return {!proto.reasoning.v1.ScenarioPropagationChunk} returns this
*/
proto.reasoning.v1.ScenarioPropagationChunk.prototype.setNodeStatesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.reasoning.v1.NodeState=} opt_value
 * @param {number=} opt_index
 * @return {!proto.reasoning.v1.NodeState}
 */
proto.reasoning.v1.ScenarioPropagationChunk.prototype.addNodeStates = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.reasoning.v1.NodeState, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reasoning.v1.ScenarioPropagationChunk} returns this
 */
proto.reasoning.v1.ScenarioPropagationChunk.prototype.clearNodeStatesList = function() {
  return this.setNodeStatesList([]);
};


/**
 * optional uint32 iteration = 2;
 * @return {number}
 */
proto.reasoning.v1.ScenarioPropagationChunk.prototype.getIteration = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.reasoning.v1.ScenarioPropagationChunk} returns this
 */
proto.reasoning.v1.ScenarioPropagationChunk.prototype.setIteration = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional bool is_final = 3;
 * @return {boolean}
 */
proto.reasoning.v1.ScenarioPropagationChunk.prototype.getIsFinal = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.reasoning.v1.ScenarioPropagationChunk} returns this
 */
proto.reasoning.v1.ScenarioPropagationChunk.prototype.setIsFinal = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool converged = 4;
 * @return {boolean}
 */
proto.reasoning.v1.ScenarioPropagationChunk.prototype.getConverged = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.reasoning.v1.ScenarioPropagationChunk} returns this
 */
proto.reasoning.v1.ScenarioPropagationChunk.prototype.setConverged = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.reasoning.v1.AnalyzeGraphRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.reasoning.v1.AnalyzeGraphRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.reasoning.v1.AnalyzeGraphRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.reasoning.v1.AnalyzeGraphRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.AnalyzeGraphRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
baseGraph: (f = msg.getBaseGraph()) && shared_graph_pb.Graph.toObject(includeInstance, f),
kindsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.reasoning.v1.AnalyzeGraphRequest}
 */
proto.reasoning.v1.AnalyzeGraphRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.reasoning.v1.AnalyzeGraphRequest;
  return proto.reasoning.v1.AnalyzeGraphRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.reasoning.v1.AnalyzeGraphRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.reasoning.v1.AnalyzeGraphRequest}
 */
proto.reasoning.v1.AnalyzeGraphRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new shared_graph_pb.Graph;
      reader.readMessage(value,shared_graph_pb.Graph.deserializeBinaryFromReader);
      msg.setBaseGraph(value);
      break;
    case 2:
      var values = /** @type {!Array<!proto.reasoning.v1.AnalysisKind>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addKinds(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.reasoning.v1.AnalyzeGraphRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.reasoning.v1.AnalyzeGraphRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.reasoning.v1.AnalyzeGraphRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.AnalyzeGraphRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBaseGraph();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      shared_graph_pb.Graph.serializeBinaryToWriter
    );
  }
  f = message.getKindsList();
  if (f.length > 0) {
    writer.writePackedEnum(
      2,
      f
    );
  }
};


/**
 * optional shared.v1.Graph base_graph = 1;
 * @return {?proto.shared.v1.Graph}
 */
proto.reasoning.v1.AnalyzeGraphRequest.prototype.getBaseGraph = function() {
  return /** @type{?proto.shared.v1.Graph} */ (
    jspb.Message.getWrapperField(this, shared_graph_pb.Graph, 1));
};


/**
 * @param {?proto.shared.v1.Graph|undefined} value
 * @return {!proto.reasoning.v1.AnalyzeGraphRequest} returns this
*/
proto.reasoning.v1.AnalyzeGraphRequest.prototype.setBaseGraph = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reasoning.v1.AnalyzeGraphRequest} returns this
 */
proto.reasoning.v1.AnalyzeGraphRequest.prototype.clearBaseGraph = function() {
  return this.setBaseGraph(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reasoning.v1.AnalyzeGraphRequest.prototype.hasBaseGraph = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated AnalysisKind kinds = 2;
 * @return {!Array<!proto.reasoning.v1.AnalysisKind>}
 */
proto.reasoning.v1.AnalyzeGraphRequest.prototype.getKindsList = function() {
  return /** @type {!Array<!proto.reasoning.v1.AnalysisKind>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<!proto.reasoning.v1.AnalysisKind>} value
 * @return {!proto.reasoning.v1.AnalyzeGraphRequest} returns this
 */
proto.reasoning.v1.AnalyzeGraphRequest.prototype.setKindsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!proto.reasoning.v1.AnalysisKind} value
 * @param {number=} opt_index
 * @return {!proto.reasoning.v1.AnalyzeGraphRequest} returns this
 */
proto.reasoning.v1.AnalyzeGraphRequest.prototype.addKinds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reasoning.v1.AnalyzeGraphRequest} returns this
 */
proto.reasoning.v1.AnalyzeGraphRequest.prototype.clearKindsList = function() {
  return this.setKindsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.reasoning.v1.NodeMetric.prototype.toObject = function(opt_includeInstance) {
  return proto.reasoning.v1.NodeMetric.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.reasoning.v1.NodeMetric} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.NodeMetric.toObject = function(includeInstance, msg) {
  var f, obj = {
nodeId: jspb.Message.getFieldWithDefault(msg, 1, ""),
metric: jspb.Message.getFieldWithDefault(msg, 2, ""),
value: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.reasoning.v1.NodeMetric}
 */
proto.reasoning.v1.NodeMetric.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.reasoning.v1.NodeMetric;
  return proto.reasoning.v1.NodeMetric.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.reasoning.v1.NodeMetric} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.reasoning.v1.NodeMetric}
 */
proto.reasoning.v1.NodeMetric.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNodeId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMetric(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.reasoning.v1.NodeMetric.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.reasoning.v1.NodeMetric.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.reasoning.v1.NodeMetric} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.NodeMetric.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNodeId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMetric();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getValue();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
};


/**
 * optional string node_id = 1;
 * @return {string}
 */
proto.reasoning.v1.NodeMetric.prototype.getNodeId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.reasoning.v1.NodeMetric} returns this
 */
proto.reasoning.v1.NodeMetric.prototype.setNodeId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string metric = 2;
 * @return {string}
 */
proto.reasoning.v1.NodeMetric.prototype.getMetric = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.reasoning.v1.NodeMetric} returns this
 */
proto.reasoning.v1.NodeMetric.prototype.setMetric = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional double value = 3;
 * @return {number}
 */
proto.reasoning.v1.NodeMetric.prototype.getValue = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.reasoning.v1.NodeMetric} returns this
 */
proto.reasoning.v1.NodeMetric.prototype.setValue = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.reasoning.v1.CycleResult.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.reasoning.v1.CycleResult.prototype.toObject = function(opt_includeInstance) {
  return proto.reasoning.v1.CycleResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.reasoning.v1.CycleResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.CycleResult.toObject = function(includeInstance, msg) {
  var f, obj = {
nodeIdsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.reasoning.v1.CycleResult}
 */
proto.reasoning.v1.CycleResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.reasoning.v1.CycleResult;
  return proto.reasoning.v1.CycleResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.reasoning.v1.CycleResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.reasoning.v1.CycleResult}
 */
proto.reasoning.v1.CycleResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addNodeIds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.reasoning.v1.CycleResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.reasoning.v1.CycleResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.reasoning.v1.CycleResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.CycleResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNodeIdsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string node_ids = 1;
 * @return {!Array<string>}
 */
proto.reasoning.v1.CycleResult.prototype.getNodeIdsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.reasoning.v1.CycleResult} returns this
 */
proto.reasoning.v1.CycleResult.prototype.setNodeIdsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.reasoning.v1.CycleResult} returns this
 */
proto.reasoning.v1.CycleResult.prototype.addNodeIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reasoning.v1.CycleResult} returns this
 */
proto.reasoning.v1.CycleResult.prototype.clearNodeIdsList = function() {
  return this.setNodeIdsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.reasoning.v1.AnalyzeGraphResponse.repeatedFields_ = [1,2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.reasoning.v1.AnalyzeGraphResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.reasoning.v1.AnalyzeGraphResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.reasoning.v1.AnalyzeGraphResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.AnalyzeGraphResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
metricsList: jspb.Message.toObjectList(msg.getMetricsList(),
    proto.reasoning.v1.NodeMetric.toObject, includeInstance),
cyclesList: jspb.Message.toObjectList(msg.getCyclesList(),
    proto.reasoning.v1.CycleResult.toObject, includeInstance),
warningsList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
meta: (f = msg.getMeta()) && shared_common_pb.ResponseMeta.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.reasoning.v1.AnalyzeGraphResponse}
 */
proto.reasoning.v1.AnalyzeGraphResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.reasoning.v1.AnalyzeGraphResponse;
  return proto.reasoning.v1.AnalyzeGraphResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.reasoning.v1.AnalyzeGraphResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.reasoning.v1.AnalyzeGraphResponse}
 */
proto.reasoning.v1.AnalyzeGraphResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.reasoning.v1.NodeMetric;
      reader.readMessage(value,proto.reasoning.v1.NodeMetric.deserializeBinaryFromReader);
      msg.addMetrics(value);
      break;
    case 2:
      var value = new proto.reasoning.v1.CycleResult;
      reader.readMessage(value,proto.reasoning.v1.CycleResult.deserializeBinaryFromReader);
      msg.addCycles(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addWarnings(value);
      break;
    case 4:
      var value = new shared_common_pb.ResponseMeta;
      reader.readMessage(value,shared_common_pb.ResponseMeta.deserializeBinaryFromReader);
      msg.setMeta(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.reasoning.v1.AnalyzeGraphResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.reasoning.v1.AnalyzeGraphResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.reasoning.v1.AnalyzeGraphResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reasoning.v1.AnalyzeGraphResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMetricsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.reasoning.v1.NodeMetric.serializeBinaryToWriter
    );
  }
  f = message.getCyclesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.reasoning.v1.CycleResult.serializeBinaryToWriter
    );
  }
  f = message.getWarningsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getMeta();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      shared_common_pb.ResponseMeta.serializeBinaryToWriter
    );
  }
};


/**
 * repeated NodeMetric metrics = 1;
 * @return {!Array<!proto.reasoning.v1.NodeMetric>}
 */
proto.reasoning.v1.AnalyzeGraphResponse.prototype.getMetricsList = function() {
  return /** @type{!Array<!proto.reasoning.v1.NodeMetric>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.reasoning.v1.NodeMetric, 1));
};


/**
 * @param {!Array<!proto.reasoning.v1.NodeMetric>} value
 * @return {!proto.reasoning.v1.AnalyzeGraphResponse} returns this
*/
proto.reasoning.v1.AnalyzeGraphResponse.prototype.setMetricsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.reasoning.v1.NodeMetric=} opt_value
 * @param {number=} opt_index
 * @return {!proto.reasoning.v1.NodeMetric}
 */
proto.reasoning.v1.AnalyzeGraphResponse.prototype.addMetrics = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.reasoning.v1.NodeMetric, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reasoning.v1.AnalyzeGraphResponse} returns this
 */
proto.reasoning.v1.AnalyzeGraphResponse.prototype.clearMetricsList = function() {
  return this.setMetricsList([]);
};


/**
 * repeated CycleResult cycles = 2;
 * @return {!Array<!proto.reasoning.v1.CycleResult>}
 */
proto.reasoning.v1.AnalyzeGraphResponse.prototype.getCyclesList = function() {
  return /** @type{!Array<!proto.reasoning.v1.CycleResult>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.reasoning.v1.CycleResult, 2));
};


/**
 * @param {!Array<!proto.reasoning.v1.CycleResult>} value
 * @return {!proto.reasoning.v1.AnalyzeGraphResponse} returns this
*/
proto.reasoning.v1.AnalyzeGraphResponse.prototype.setCyclesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.reasoning.v1.CycleResult=} opt_value
 * @param {number=} opt_index
 * @return {!proto.reasoning.v1.CycleResult}
 */
proto.reasoning.v1.AnalyzeGraphResponse.prototype.addCycles = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.reasoning.v1.CycleResult, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reasoning.v1.AnalyzeGraphResponse} returns this
 */
proto.reasoning.v1.AnalyzeGraphResponse.prototype.clearCyclesList = function() {
  return this.setCyclesList([]);
};


/**
 * repeated string warnings = 3;
 * @return {!Array<string>}
 */
proto.reasoning.v1.AnalyzeGraphResponse.prototype.getWarningsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.reasoning.v1.AnalyzeGraphResponse} returns this
 */
proto.reasoning.v1.AnalyzeGraphResponse.prototype.setWarningsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.reasoning.v1.AnalyzeGraphResponse} returns this
 */
proto.reasoning.v1.AnalyzeGraphResponse.prototype.addWarnings = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reasoning.v1.AnalyzeGraphResponse} returns this
 */
proto.reasoning.v1.AnalyzeGraphResponse.prototype.clearWarningsList = function() {
  return this.setWarningsList([]);
};


/**
 * optional shared.v1.ResponseMeta meta = 4;
 * @return {?proto.shared.v1.ResponseMeta}
 */
proto.reasoning.v1.AnalyzeGraphResponse.prototype.getMeta = function() {
  return /** @type{?proto.shared.v1.ResponseMeta} */ (
    jspb.Message.getWrapperField(this, shared_common_pb.ResponseMeta, 4));
};


/**
 * @param {?proto.shared.v1.ResponseMeta|undefined} value
 * @return {!proto.reasoning.v1.AnalyzeGraphResponse} returns this
*/
proto.reasoning.v1.AnalyzeGraphResponse.prototype.setMeta = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reasoning.v1.AnalyzeGraphResponse} returns this
 */
proto.reasoning.v1.AnalyzeGraphResponse.prototype.clearMeta = function() {
  return this.setMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reasoning.v1.AnalyzeGraphResponse.prototype.hasMeta = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * @enum {number}
 */
proto.reasoning.v1.PerturbationDirection = {
  PERTURBATION_DIRECTION_UNSPECIFIED: 0,
  PERTURBATION_DIRECTION_INCREASE: 1,
  PERTURBATION_DIRECTION_DECREASE: 2,
  PERTURBATION_DIRECTION_SET: 3
};

/**
 * @enum {number}
 */
proto.reasoning.v1.AnalysisKind = {
  ANALYSIS_KIND_UNSPECIFIED: 0,
  ANALYSIS_KIND_CENTRALITY: 1,
  ANALYSIS_KIND_CYCLES: 2,
  ANALYSIS_KIND_INFLUENCE: 3,
  ANALYSIS_KIND_SHORTEST_PATH: 4
};

goog.object.extend(exports, proto.reasoning.v1);
