/**
 * @fileoverview gRPC-Web generated client stub for reasoning.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: reasoning/reasoning.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as reasoning_reasoning_pb from '../reasoning/reasoning_pb'; // proto import: "reasoning/reasoning.proto"


export class ReasoningServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorBuildConceptGraph = new grpcWeb.MethodDescriptor(
    '/reasoning.v1.ReasoningService/BuildConceptGraph',
    grpcWeb.MethodType.UNARY,
    reasoning_reasoning_pb.BuildConceptGraphRequest,
    reasoning_reasoning_pb.BuildConceptGraphResponse,
    (request: reasoning_reasoning_pb.BuildConceptGraphRequest) => {
      return request.serializeBinary();
    },
    reasoning_reasoning_pb.BuildConceptGraphResponse.deserializeBinary
  );

  buildConceptGraph(
    request: reasoning_reasoning_pb.BuildConceptGraphRequest,
    metadata?: grpcWeb.Metadata | null): Promise<reasoning_reasoning_pb.BuildConceptGraphResponse>;

  buildConceptGraph(
    request: reasoning_reasoning_pb.BuildConceptGraphRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: reasoning_reasoning_pb.BuildConceptGraphResponse) => void): grpcWeb.ClientReadableStream<reasoning_reasoning_pb.BuildConceptGraphResponse>;

  buildConceptGraph(
    request: reasoning_reasoning_pb.BuildConceptGraphRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: reasoning_reasoning_pb.BuildConceptGraphResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/reasoning.v1.ReasoningService/BuildConceptGraph',
        request,
        metadata || {},
        this.methodDescriptorBuildConceptGraph,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/reasoning.v1.ReasoningService/BuildConceptGraph',
    request,
    metadata || {},
    this.methodDescriptorBuildConceptGraph);
  }

  methodDescriptorRunScenario = new grpcWeb.MethodDescriptor(
    '/reasoning.v1.ReasoningService/RunScenario',
    grpcWeb.MethodType.UNARY,
    reasoning_reasoning_pb.RunScenarioRequest,
    reasoning_reasoning_pb.RunScenarioResponse,
    (request: reasoning_reasoning_pb.RunScenarioRequest) => {
      return request.serializeBinary();
    },
    reasoning_reasoning_pb.RunScenarioResponse.deserializeBinary
  );

  runScenario(
    request: reasoning_reasoning_pb.RunScenarioRequest,
    metadata?: grpcWeb.Metadata | null): Promise<reasoning_reasoning_pb.RunScenarioResponse>;

  runScenario(
    request: reasoning_reasoning_pb.RunScenarioRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: reasoning_reasoning_pb.RunScenarioResponse) => void): grpcWeb.ClientReadableStream<reasoning_reasoning_pb.RunScenarioResponse>;

  runScenario(
    request: reasoning_reasoning_pb.RunScenarioRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: reasoning_reasoning_pb.RunScenarioResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/reasoning.v1.ReasoningService/RunScenario',
        request,
        metadata || {},
        this.methodDescriptorRunScenario,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/reasoning.v1.ReasoningService/RunScenario',
    request,
    metadata || {},
    this.methodDescriptorRunScenario);
  }

  methodDescriptorRunScenarioStream = new grpcWeb.MethodDescriptor(
    '/reasoning.v1.ReasoningService/RunScenarioStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    reasoning_reasoning_pb.RunScenarioRequest,
    reasoning_reasoning_pb.ScenarioPropagationChunk,
    (request: reasoning_reasoning_pb.RunScenarioRequest) => {
      return request.serializeBinary();
    },
    reasoning_reasoning_pb.ScenarioPropagationChunk.deserializeBinary
  );

  runScenarioStream(
    request: reasoning_reasoning_pb.RunScenarioRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<reasoning_reasoning_pb.ScenarioPropagationChunk> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/reasoning.v1.ReasoningService/RunScenarioStream',
      request,
      metadata || {},
      this.methodDescriptorRunScenarioStream);
  }

  methodDescriptorAnalyzeGraph = new grpcWeb.MethodDescriptor(
    '/reasoning.v1.ReasoningService/AnalyzeGraph',
    grpcWeb.MethodType.UNARY,
    reasoning_reasoning_pb.AnalyzeGraphRequest,
    reasoning_reasoning_pb.AnalyzeGraphResponse,
    (request: reasoning_reasoning_pb.AnalyzeGraphRequest) => {
      return request.serializeBinary();
    },
    reasoning_reasoning_pb.AnalyzeGraphResponse.deserializeBinary
  );

  analyzeGraph(
    request: reasoning_reasoning_pb.AnalyzeGraphRequest,
    metadata?: grpcWeb.Metadata | null): Promise<reasoning_reasoning_pb.AnalyzeGraphResponse>;

  analyzeGraph(
    request: reasoning_reasoning_pb.AnalyzeGraphRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: reasoning_reasoning_pb.AnalyzeGraphResponse) => void): grpcWeb.ClientReadableStream<reasoning_reasoning_pb.AnalyzeGraphResponse>;

  analyzeGraph(
    request: reasoning_reasoning_pb.AnalyzeGraphRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: reasoning_reasoning_pb.AnalyzeGraphResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/reasoning.v1.ReasoningService/AnalyzeGraph',
        request,
        metadata || {},
        this.methodDescriptorAnalyzeGraph,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/reasoning.v1.ReasoningService/AnalyzeGraph',
    request,
    metadata || {},
    this.methodDescriptorAnalyzeGraph);
  }

}

